In [4]:
import requests
import pandas as pd

url = "https://data-api.polymarket.com/v2/trades"

response = requests.get(url)

print(response.status_code)

data = response.json()["data"]

df = pd.DataFrame(data)

print(df.shape)
print(df.columns)
df.head()

200
(100, 19)
Index(['proxy_wallet', 'side', 'token_id', 'condition_id', 'size', 'price',
       'timestamp', 'title', 'slug', 'icon', 'event_slug', 'outcome',
       'outcome_index', 'name', 'pseudonym', 'bio', 'profile_image',
       'profile_image_optimized', 'transaction_hash'],
      dtype='object')

,proxy_wallet,side,token_id,condition_id,size,price,timestamp,title,slug,icon,event_slug,outcome,outcome_index,name,pseudonym,bio,profile_image,profile_image_optimized,transaction_hash
0,0xc69bd5567b40ef4d11922eaa57e1f9be1c642076,BUY,3333979837291603722078613613340647849111615062...,0xefa17dee3af09f69f9ddf245b969aa4efbe7c71cdf06...,5.00,0.002000,1791480578,Will Shakhtar Donetsk win the 2026-27 UEFA Cha...,will-shakhtar-donetsk-win-the-2026-27-uefa-cha...,,uefa-champions-league-2027-champion-2026070120...,Yes,0,vtcchampion52,Ultimate-Underpass,grandmaster fiora,https://polymarket-upload.s3.us-east-2.amazona...,,0xd1b66f1497a0c2245af28a4b6ec1a59489679667e4bf...
1,0xe3eb836b52c0dcbe23dc81d81d212aa79dda69e8,SELL,1853497609396914241067854182138353409013655981...,0x171fdeb14774ff4f26155d8dc9e4b97d2c1f12e0c99b...,0.03,0.001000,1791480576,Will the highest temperature in Dallas be betw...,highest-temperature-in-dallas-on-october-8-202...,https://polymarket-upload.s3.us-east-2.amazona...,highest-temperature-in-dallas-on-october-8-2026,Yes,0,bigProfiter,Previous-Marshmallow-Offer,,,,0x2eb8f670e6f4802a76ea5febb8b526a100ceb7f0cfd3...
2,0xc69bd5567b40ef4d11922eaa57e1f9be1c642076,BUY,3333979837291603722078613613340647849111615062...,0xefa17dee3af09f69f9ddf245b969aa4efbe7c71cdf06...,5.00,0.002000,1791480576,Will Shakhtar Donetsk win the 2026-27 UEFA Cha...,will-shakhtar-donetsk-win-the-2026-27-uefa-cha...,,uefa-champions-league-2027-champion-2026070120...,Yes,0,vtcchampion52,Ultimate-Underpass,grandmaster fiora,https://polymarket-upload.s3.us-east-2.amazona...,,0x908d64b28c7c005463d60c66207282780346db93f993...
3,0xf1ee4842fa0c7283632185e42577027452d4519c,BUY,4758400483007998806022531916427355725972661800...,0xb1cc2d4b2f8e0a8611c0111df2a6dc0102622ef38edb...,47.98,0.368958,1791480576,Counter-Strike: FaZe vs Sangal (BO3) - Roman I...,cs2-faze-sng2-2026-10-08,https://polymarket-upload.s3.us-east-2.amazona...,cs2-faze-sng2-2026-10-08,Sangal,1,Jimmyman132,Scary-Billboard,,,,0x6a597de855a5c1e059976496bc6cbfd76feecc9b5ca4...
4,0xc69bd5567b40ef4d11922eaa57e1f9be1c642076,BUY,3333979837291603722078613613340647849111615062...,0xefa17dee3af09f69f9ddf245b969aa4efbe7c71cdf06...,5.00,0.002000,1791480576,Will Shakhtar Donetsk win the 2026-27 UEFA Cha...,will-shakhtar-donetsk-win-the-2026-27-uefa-cha...,,uefa-champions-league-2027-champion-2026070120...,Yes,0,vtcchampion52,Ultimate-Underpass,grandmaster fiora,https://polymarket-upload.s3.us-east-2.amazona...,,0xbc3486e9c3958670d22b2dacb4d67b2fead16493c2a3...

In [5]:
import requests
import pandas as pd
import time

url = "https://data-api.polymarket.com/v2/trades"

all_trades = []
cursor = None

for page in range(10):

    params = {
        "limit": 1000
    }

    if cursor:
        params["cursor"] = cursor

    response = requests.get(url, params=params)

    print("Page:", page + 1, "Status:", response.status_code)

    data = response.json()

    trades = data.get("data", [])
    all_trades.extend(trades)

    print("Trades collected:", len(all_trades))

    pagination = data.get("pagination", {})
    cursor = pagination.get("next_cursor")

    if not cursor:
        print("Finished!")
        break

    time.sleep(0.2)

df = pd.DataFrame(all_trades)

print()
print("TOTAL TRADES:", len(df))
print("COLUMNS:")
print(df.columns.tolist())

Page: 1 Status: 200
Trades collected: 1000
Page: 2 Status: 200
Trades collected: 2000
Page: 3 Status: 200
Trades collected: 3000
Page: 4 Status: 200
Trades collected: 4000
Page: 5 Status: 200
Trades collected: 5000
Page: 6 Status: 200
Trades collected: 6000
Page: 7 Status: 200
Trades collected: 7000
Page: 8 Status: 200
Trades collected: 8000
Page: 9 Status: 200
Trades collected: 9000
Page: 10 Status: 200
Trades collected: 10000

TOTAL TRADES: 10000
COLUMNS:
['proxy_wallet', 'side', 'token_id', 'condition_id', 'size', 'price', 'timestamp', 'title', 'slug', 'icon', 'event_slug', 'outcome', 'outcome_index', 'name', 'pseudonym', 'bio', 'profile_image', 'profile_image_optimized', 'transaction_hash']

In [6]:
print(df["timestamp"].head(10))
print(df["timestamp"].min(), df["timestamp"].max())

0    1791480534
1    1791480534
2    1791480534
3    1791480533
4    1791480533
5    1791480533
6    1791480533
7    1791480533
8    1791480533
9    1791480533
Name: timestamp, dtype: int64
1791479939 1791480534

In [7]:
df["date"] = pd.to_datetime(df["timestamp"], unit="s")

print(df[["timestamp", "date"]].head(10))

    timestamp                date
0  1791480534 2026-10-08 17:28:54
1  1791480534 2026-10-08 17:28:54
2  1791480534 2026-10-08 17:28:54
3  1791480533 2026-10-08 17:28:53
4  1791480533 2026-10-08 17:28:53
5  1791480533 2026-10-08 17:28:53
6  1791480533 2026-10-08 17:28:53
7  1791480533 2026-10-08 17:28:53
8  1791480533 2026-10-08 17:28:53
9  1791480533 2026-10-08 17:28:53

In [8]:
df["date"] = pd.to_datetime(df["timestamp"], unit="s")
print(df[["timestamp", "date"]].head(10))

    timestamp                date
0  1791480534 2026-10-08 17:28:54
1  1791480534 2026-10-08 17:28:54
2  1791480534 2026-10-08 17:28:54
3  1791480533 2026-10-08 17:28:53
4  1791480533 2026-10-08 17:28:53
5  1791480533 2026-10-08 17:28:53
6  1791480533 2026-10-08 17:28:53
7  1791480533 2026-10-08 17:28:53
8  1791480533 2026-10-08 17:28:53
9  1791480533 2026-10-08 17:28:53

In [9]:
import requests
import pandas as pd

url = "https://gamma-api.polymarket.com/markets"

params = {
    "closed": True,
    "end_date_min": "2025-11-01T00:00:00Z",
    "end_date_max": "2026-05-01T00:00:00Z",
    "limit": 100
}

response = requests.get(url, params=params)

print("Status:", response.status_code)

markets = response.json()

print("Markets found:", len(markets))

markets_df = pd.DataFrame(markets)

print(markets_df.columns.tolist())
markets_df.head()

Status: 200
Markets found: 100
['id', 'question', 'conditionId', 'slug', 'resolutionSource', 'endDate', 'startDate', 'image', 'icon', 'description', 'outcomes', 'outcomePrices', 'volume', 'active', 'closed', 'marketMakerAddress', 'createdAt', 'updatedAt', 'closedTime', 'new', 'featured', 'submitted_by', 'archived', 'resolvedBy', 'restricted', 'groupItemTitle', 'groupItemThreshold', 'questionID', 'umaEndDate', 'enableOrderBook', 'orderPriceMinTickSize', 'orderMinSize', 'umaResolutionStatus', 'volumeNum', 'endDateIso', 'startDateIso', 'hasReviewedDates', 'volume1wk', 'volume1mo', 'volume1yr', 'clobTokenIds', 'comboStatus', 'umaBond', 'umaReward', 'volume1wkAmm', 'volume1moAmm', 'volume1yrAmm', 'volume1wkClob', 'volume1moClob', 'volume1yrClob', 'volumeClob', 'acceptingOrders', 'negRisk', 'events', 'ready', 'funded', 'acceptingOrdersTimestamp', 'cyom', 'approved', 'clobRewards', 'rewardsMinSize', 'rewardsMaxSpread', 'spread', 'automaticallyResolved', 'oneDayPriceChange', 'oneHourPriceChange', 'oneWeekPriceChange', 'oneMonthPriceChange', 'oneYearPriceChange', 'lastTradePrice', 'bestAsk', 'automaticallyActive', 'clearBookOnStart', 'manualActivation', 'negRiskOther', 'umaResolutionStatuses', 'pendingDeployment', 'deploying', 'rfqEnabled', 'holdingRewardsEnabled', 'feesEnabled', 'feeType', 'version', 'bestBid', 'gameStartTime', 'customLiveness', 'seriesColor', 'showGmpSeries', 'showGmpOutcome', 'negRiskMarketID', 'negRiskRequestID', 'liquidity', 'liquidityNum', 'liquidityAmm', 'liquidityClob', 'competitive', 'makerBaseFee', 'takerBaseFee', 'feeSchedule']

,id,question,conditionId,slug,resolutionSource,endDate,startDate,image,icon,description,...,negRiskMarketID,negRiskRequestID,liquidity,liquidityNum,liquidityAmm,liquidityClob,competitive,makerBaseFee,takerBaseFee,feeSchedule
0,515928,Greens win over 15% of vote in German election?,0x19f0ff3845b991bf9561aa81f7a23d88a607a437a6ec...,will-the-greens-win-over-15-of-the-vote-in-the...,,2025-12-31T12:00:00Z,2024-12-17T22:36:59.555Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,German Federal elections to elect the 21st Bun...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,516493,Will Microstrategy vote to increase common sto...,0x2b247ca3101b16d95afcb5117a03a126c6a767d31318...,will-microstrategy-vote-to-increase-common-sto...,,2025-12-31T12:00:00Z,2024-12-30T18:35:50.260352Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,Microstrategy announced they will hold a vote ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,516706,Fed rate hike in 2025?,0x4319532e181605cb15b1bd677759a3bc7f7394b2fdf1...,fed-rate-hike-in-2025,,2025-12-10T12:00:00Z,2024-12-29T22:50:33.584839Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,This market will resolve to “Yes” if the upper...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,516707,Circle IPO in 2025?,0x0d960ee751036fdae09a4b318de8aa40f74b71cc8943...,circle-ipo-in-2025,,2025-12-31T12:00:00Z,2024-12-29T22:43:32.373Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,"This market will resolve to ""Yes"" if Circle co...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,516710,US recession in 2025?,0xfa48a99317daef1654d5b03e30557c4222f276657275...,us-recession-in-2025,,2026-02-28T12:00:00Z,2025-01-08T01:33:54.924Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,"This market will resolve to “Yes”, if either o...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
import requests
import pandas as pd
import time

url = "https://gamma-api.polymarket.com/markets"

all_markets = []
offset = 0
limit = 100

while True:

    params = {
        "closed": True,
        "end_date_min": "2025-11-01T00:00:00Z",
        "end_date_max": "2026-05-01T00:00:00Z",
        "limit": limit,
        "offset": offset
    }

    response = requests.get(url, params=params)

    print("Offset:", offset, "Status:", response.status_code)

    markets = response.json()

    if not markets:
        break

    all_markets.extend(markets)

    print("Markets collected:", len(all_markets))

    if len(markets) < limit:
        break

    offset += limit

    time.sleep(0.2)

markets_df = pd.DataFrame(all_markets)

print()
print("TOTAL MARKETS:", len(markets_df))
markets_df[[
    "id",
    "question",
    "conditionId",
    "startDate",
    "endDate"
]].head(10)

Offset: 0 Status: 200
Markets collected: 100
Offset: 100 Status: 200
Markets collected: 200
Offset: 200 Status: 200
Markets collected: 300
Offset: 300 Status: 200
Markets collected: 400
Offset: 400 Status: 200
Markets collected: 500
Offset: 500 Status: 200
Markets collected: 600
Offset: 600 Status: 200
Markets collected: 700
Offset: 700 Status: 200
Markets collected: 800
Offset: 800 Status: 200
Markets collected: 900
Offset: 900 Status: 200
Markets collected: 1000
Offset: 1000 Status: 200
Markets collected: 1100
Offset: 1100 Status: 200
Markets collected: 1200
Offset: 1200 Status: 200
Markets collected: 1300
Offset: 1300 Status: 200
Markets collected: 1400
Offset: 1400 Status: 200
Markets collected: 1500
Offset: 1500 Status: 200
Markets collected: 1600
Offset: 1600 Status: 200
Markets collected: 1700
Offset: 1700 Status: 200
Markets collected: 1800
Offset: 1800 Status: 200
Markets collected: 1900
Offset: 1900 Status: 200
Markets collected: 2000
Offset: 2000 Status: 200
Markets collected: 2100
Offset: 2100 Status: 422
Markets collected: 2102

AttributeError: 'str' object has no attribute 'keys'

In [12]:
# Оставляем только нормальные записи-словари
valid_markets = [m for m in all_markets if isinstance(m, dict)]

markets_df = pd.DataFrame(valid_markets)

print("Нормальных рынков:", len(markets_df))
print(markets_df[[
    "id",
    "question",
    "conditionId",
    "startDate",
    "endDate"
]].head(10))

Нормальных рынков: 2100
       id                                           question  \
0  515928   Greens win over 15% of vote in German election?
1  516493  Will Microstrategy vote to increase common sto...
2  516706                             Fed rate hike in 2025?
3  516707                                Circle IPO in 2025?
4  516710                              US recession in 2025?
5  516711                    Fed emergency rate cut in 2025?
6  516712                          Tether insolvent in 2025?
7  516713                                USDT depeg in 2025?
8  516714                          Weed rescheduled in 2025?
9  516715                        Ukraine joins NATO in 2025?

                                         conditionId  \
0  0x19f0ff3845b991bf9561aa81f7a23d88a607a437a6ec...
1  0x2b247ca3101b16d95afcb5117a03a126c6a767d31318...
2  0x4319532e181605cb15b1bd677759a3bc7f7394b2fdf1...
3  0x0d960ee751036fdae09a4b318de8aa40f74b71cc8943...
4  0xfa48a99317daef1654d5b03e30557c4222f276657275...
5  0xcddb4f52babca280f8e5fc4b9146f2520f0bfb88e134...
6  0x1bbdc459d73e6972f5ba1f687d739fde70a9774f4875...
7  0x416316490efec1038ce09ec0184f82f1f7921876ee05...
8  0x5a54c2fe06f97a6abf5f7790d9d19e42680ae1ca61b3...
9  0x9bacdaac65cbe257e96e58daf343c56879ea9003bdae...

                     startDate               endDate
0     2024-12-17T22:36:59.555Z  2025-12-31T12:00:00Z
1  2024-12-30T18:35:50.260352Z  2025-12-31T12:00:00Z
2  2024-12-29T22:50:33.584839Z  2025-12-10T12:00:00Z
3     2024-12-29T22:43:32.373Z  2025-12-31T12:00:00Z
4     2025-01-08T01:33:54.924Z  2026-02-28T12:00:00Z
5      2024-12-29T22:41:48.24Z  2025-12-31T12:00:00Z
6     2024-12-29T22:41:19.741Z  2025-12-31T12:00:00Z
7  2024-12-29T22:40:52.581438Z  2025-12-31T12:00:00Z
8     2024-12-29T22:52:12.219Z  2025-12-31T12:00:00Z
9     2024-12-29T22:40:28.804Z  2025-12-31T12:00:00Z

In [ ]:
# Приводим volume к числу
markets_df["volume"] = pd.to_numeric(
    markets_df["volume"],
    errors="coerce"
)

# Сортируем рынки по объёму
top_markets = markets_df.sort_values(
    "volume",
    ascending=False
).head(200)

print("Топ-200 рынков:")
print(top_markets[[
    "question",
    "volume",
    "startDate",
    "endDate",
    "conditionId"
]].head(20))

In [ ]:
market = top_markets.iloc[0]

print("Market:")
print(market["question"])

print()
print("Condition ID:")
print(market["conditionId"])

In [ ]:
import requests
import pandas as pd
import time

condition_id = market["conditionId"]

url = "https://data-api.polymarket.com/v2/trades"

all_trades = []
cursor = None

for page in range(20):

    params = {
        "condition": condition_id,
        "limit": 1000
    }

    if cursor:
        params["cursor"] = cursor

    response = requests.get(url, params=params)

    print("Page:", page + 1, "Status:", response.status_code)

    data = response.json()

    trades = data.get("data", [])
    all_trades.extend(trades)

    print("Trades collected:", len(all_trades))

    pagination = data.get("pagination", {})
    cursor = pagination.get("next_cursor")

    if not cursor:
        print("Finished!")
        break

    time.sleep(0.2)

trades_df = pd.DataFrame(all_trades)

print()
print("TOTAL TRADES:", len(trades_df))

In [ ]:
import requests
import pandas as pd
import time

condition_id = market["conditionId"]

url = "https://data-api.polymarket.com/v2/trades"

all_trades = []
cursor = None
page = 0

while True:

    params = {
        "condition": condition_id,
        "limit": 1000
    }

    if cursor:
        params["cursor"] = cursor

    response = requests.get(url, params=params)

    print("Page:", page + 1, "Status:", response.status_code)

    if response.status_code != 200:
        print("API error:", response.text)
        break

    data = response.json()

    trades = data.get("data", [])
    all_trades.extend(trades)

    print("Trades collected:", len(all_trades))

    pagination = data.get("pagination", {})
    cursor = pagination.get("next_cursor")

    page += 1

    if not cursor:
        print("Finished!")
        break

    time.sleep(0.2)

trades_df = pd.DataFrame(all_trades)

print()
print("TOTAL TRADES:", len(trades_df))

In [ ]:
print("Уникальных кошельков:", trades_df["proxy_wallet"].nunique())

print()
print("Уникальных транзакций:", trades_df["transaction_hash"].nunique())

print()
print("Период:")
trades_df["date"] = pd.to_datetime(
    trades_df["timestamp"],
    unit="s",
    utc=True
)

print("От:", trades_df["date"].min())
print("До:", trades_df["date"].max())

In [ ]:
print(trades_df["side"].value_counts())
print()
print(trades_df["outcome"].value_counts())

In [ ]:
top_30_markets = markets_df.sort_values(
    "volume",
    ascending=False
).head(30).copy()

print("Количество рынков:", len(top_30_markets))

print(
    top_30_markets[[
        "question",
        "volume",
        "startDate",
        "endDate"
    ]].to_string(index=False)
)

In [ ]:
# Оставляем только сделки в нашем исследовательском периоде

start_date = pd.Timestamp("2025-11-01", tz="UTC")
end_date = pd.Timestamp("2026-05-01", tz="UTC")

period_trades = trades_df[
    (trades_df["date"] >= start_date) &
    (trades_df["date"] < end_date)
].copy()

print("Сделок в исследуемом периоде:", len(period_trades))

print(
    "Уникальных кошельков:",
    period_trades["proxy_wallet"].nunique()
)

print(
    "Период:",
    period_trades["date"].min(),
    "→",
    period_trades["date"].max()
)

In [ ]:
wallet_stats = (
    period_trades
    .groupby("proxy_wallet")
    .agg(
        trades=("proxy_wallet", "size"),
        volume=("size", "sum"),
        avg_price=("price", "mean")
    )
    .sort_values("volume", ascending=False)
)

wallet_stats.head(20)

In [ ]:
print("Всего кошельков:", len(wallet_stats))
print("Среднее число сделок:", wallet_stats["trades"].mean())
print("Медиана сделок:", wallet_stats["trades"].median())
print("Максимум сделок у одного кошелька:", wallet_stats["trades"].max())

In [ ]:
wallet_outcomes = (
    period_trades
    .groupby(["proxy_wallet", "outcome"])
    .agg(
        trades=("proxy_wallet", "size"),
        volume=("size", "sum")
    )
    .reset_index()
)

wallet_outcomes.sort_values("volume", ascending=False).head(30)

In [ ]:
bot_wallet = "0x3f7aee8f1fafcd873343105b24f83f3f98a9248e"

bot_trades = period_trades[
    period_trades["proxy_wallet"] == bot_wallet
].copy()

print("Сделок:", len(bot_trades))
print("Средний размер:", bot_trades["size"].mean())
print("Медианный размер:", bot_trades["size"].median())
print("Максимальный размер:", bot_trades["size"].max())

print("\nРынки:")
print(bot_trades["title"].value_counts().head(10))

In [ ]:
bot_trades = bot_trades.sort_values("date").copy()

bot_trades["seconds_between"] = (
    bot_trades["date"].diff().dt.total_seconds()
)

print(bot_trades["seconds_between"].describe())

In [ ]:
print(market["question"])
print("Resolution:", market.get("resolutionSource"))
print("End date:", market.get("endDate"))
print("Outcomes:", market.get("outcomes"))
print("Outcome prices:", market.get("outcomePrices"))

In [ ]:
wallet_result = (
    period_trades
    .groupby(["proxy_wallet", "outcome"])
    .agg(
        trades=("proxy_wallet", "size"),
        volume=("size", "sum"),
        avg_price=("price", "mean")
    )
    .reset_index()
)

wallet_result["result"] = wallet_result["outcome"].map({
    "Yes": "WIN",
    "No": "LOSE"
})

wallet_result = wallet_result.sort_values("volume", ascending=False)

wallet_result.head(30)

In [ ]:
interesting_wallet = "0xe0ac9addc56c19e771a0524f5d172af4d7a476ff"

w = period_trades[
    period_trades["proxy_wallet"] == interesting_wallet
].copy()

print(
    w[
        ["date", "side", "outcome", "size", "price"]
    ].sort_values("date").to_string(index=False)
)

In [ ]:
resolution = pd.Timestamp("2025-11-04T12:00:00Z")

w["time_to_resolution"] = resolution - w["date"]

print(
    w[
        ["date", "side", "outcome", "size", "price", "time_to_resolution"]
    ].sort_values("date").to_string(index=False)
)

In [ ]:
# Смотрим все поля, которые могут быть связаны
# с закрытием / разрешением рынка

important_fields = [
    "id",
    "question",
    "conditionId",
    "slug",
    "startDate",
    "endDate",
    "closed",
    "closedTime",
    "active",
    "archived",
    "outcomes",
    "outcomePrices",
    "resolutionSource",
    "resolvedBy",
    "umaResolutionStatus",
    "umaEndDate",
    "description"
]

for field in important_fields:
    print(f"{field}:")
    print(market.get(field))
    print()

In [ ]:
resolution_time = pd.Timestamp("2025-11-05T05:44:47Z")

period_trades["hours_to_resolution"] = (
    resolution_time - period_trades["date"]
).dt.total_seconds() / 3600

print(
    period_trades[
        ["date", "proxy_wallet", "side", "outcome",
         "size", "price", "hours_to_resolution"]
    ].head()
)

In [ ]:
winning_outcome = "Yes"

candidate_trades = period_trades[
    (period_trades["outcome"] == winning_outcome) &
    (period_trades["side"] == "BUY") &
    (period_trades["hours_to_resolution"] >= 0) &
    (period_trades["hours_to_resolution"] <= 24)
].copy()

candidate_trades["notional"] = (
    candidate_trades["size"] * candidate_trades["price"]
)

print("Количество BUY:", len(candidate_trades))

candidate_trades.sort_values(
    ["hours_to_resolution", "notional"],
    ascending=[True, False]
)[[
    "date",
    "proxy_wallet",
    "side",
    "outcome",
    "size",
    "price",
    "notional",
    "hours_to_resolution"
]].head(30)

In [ ]:
interesting_buys = candidate_trades[
    candidate_trades["price"] < 0.90
].copy()

print("BUY Yes дешевле 0.90:", len(interesting_buys))

interesting_buys.sort_values(
    "notional",
    ascending=False
)[[
    "date",
    "proxy_wallet",
    "size",
    "price",
    "notional",
    "hours_to_resolution"
]].head(30)

In [ ]:
interesting_buys.sort_values(
    ["price", "notional"],
    ascending=[True, False]
)[[
    "date",
    "proxy_wallet",
    "size",
    "price",
    "notional",
    "hours_to_resolution"
]].head(30)

In [ ]:
price_by_hour = (
    period_trades
    .groupby(period_trades["hours_to_resolution"].round())
    ["price"]
    .mean()
    .sort_index(ascending=False)
)

print(price_by_hour)

In [ ]:
early_buys = period_trades[
    (period_trades["outcome"] == "Yes") &
    (period_trades["side"] == "BUY") &
    (period_trades["hours_to_resolution"] >= 24) &
    (period_trades["price"] <= 0.70)
].copy()

early_buys["notional"] = (
    early_buys["size"] * early_buys["price"]
)

print("Ранних BUY:", len(early_buys))

early_buys.sort_values(
    "notional",
    ascending=False
)[[
    "date",
    "proxy_wallet",
    "size",
    "price",
    "notional",
    "hours_to_resolution"
]].head(30)

In [ ]:
early_buys = period_trades[
    (period_trades["outcome"] == "Yes") &
    (period_trades["side"] == "BUY") &
    (period_trades["hours_to_resolution"] >= 24) &
    (period_trades["hours_to_resolution"] <= 72)
].copy()

early_buys["notional"] = (
    early_buys["size"] * early_buys["price"]
)

print("BUY за 24–72 часа:", len(early_buys))

early_buys.sort_values(
    "notional",
    ascending=False
)[[
    "date",
    "proxy_wallet",
    "size",
    "price",
    "notional",
    "hours_to_resolution"
]].head(30)

In [ ]:
wallet = "0x7702028f87deda0ceefea619209ece9630669791"

wallet_trades = period_trades[
    period_trades["proxy_wallet"] == wallet
].copy()

wallet_trades["notional"] = (
    wallet_trades["size"] * wallet_trades["price"]
)

wallet_trades[
    [
        "date",
        "side",
        "outcome",
        "size",
        "price",
        "notional",
        "hours_to_resolution"
    ]
].sort_values("date")

In [ ]:
wallet = "0x7702028f87deda0ceefea619209ece9630669791"

wallet_trades = period_trades[
    period_trades["proxy_wallet"] == wallet
].copy()

print(
    wallet_trades[
        ["date", "side", "price", "notional", "hours_to_resolution"]
    ].sort_values("date").to_string(index=False)
)

In [ ]:
wallet = "0x7702028f87deda0ceefea619209ece9630669791"

wallet_trades = period_trades[
    period_trades["proxy_wallet"] == wallet
].copy()

# Считаем денежный объём сделки
wallet_trades["notional"] = (
    wallet_trades["size"] * wallet_trades["price"]
)

print(
    wallet_trades[
        ["date", "side", "outcome", "price", "notional", "hours_to_resolution"]
    ]
    .sort_values("date")
    .to_string(index=False)
)

In [ ]:
buy_time = pd.Timestamp("2025-11-02 22:09:37+00:00")

future_trades = period_trades[
    (period_trades["date"] >= buy_time) &
    (period_trades["date"] <= buy_time + pd.Timedelta(hours=1))
].copy()

print(
    future_trades[
        ["date", "side", "price", "size"]
    ].head(20).to_string(index=False)
)

In [ ]:
large_buys = wallet_trades[
    (wallet_trades["side"] == "BUY") &
    (wallet_trades["notional"] >= 10000)
].copy()

print(
    large_buys[
        ["date", "price", "notional", "hours_to_resolution"]
    ].sort_values("date").to_string(index=False)
)

In [ ]:
def price_after_hours(trades, buy_time, hours):
    target_time = buy_time + pd.Timedelta(hours=hours)

    future = trades[
        trades["date"] >= target_time
    ].sort_values("date")

    if len(future) == 0:
        return None

    return future.iloc[0]["price"]

In [ ]:
large_buys = period_trades[
    (period_trades["side"] == "BUY") &
    (period_trades["outcome"] == "Yes") &
    (period_trades["size"] * period_trades["price"] >= 10000)
].copy()

large_buys["notional"] = (
    large_buys["size"] * large_buys["price"]
)

print("Крупных BUY:", len(large_buys))

In [ ]:
large_buys["price_1h"] = large_buys["date"].apply(
    lambda x: price_after_hours(period_trades, x, 1)
)

large_buys["price_3h"] = large_buys["date"].apply(
    lambda x: price_after_hours(period_trades, x, 3)
)

large_buys["price_6h"] = large_buys["date"].apply(
    lambda x: price_after_hours(period_trades, x, 6)
)

large_buys["move_1h"] = (
    large_buys["price_1h"] - large_buys["price"]
)

large_buys["move_3h"] = (
    large_buys["price_3h"] - large_buys["price"]
)

large_buys["move_6h"] = (
    large_buys["price_6h"] - large_buys["price"]
)

In [ ]:
result = large_buys.sort_values(
    "move_3h",
    ascending=False
)

print(
    result[
        [
            "date",
            "proxy_wallet",
            "notional",
            "price",
            "price_1h",
            "price_3h",
            "price_6h",
            "move_1h",
            "move_3h",
            "move_6h"
        ]
    ].head(30).to_string(index=False)
)

In [ ]:
def price_after_hours(trades, buy_time, hours, outcome):
    target_time = buy_time + pd.Timedelta(hours=hours)

    future = trades[
        (trades["date"] >= target_time) &
        (trades["outcome"] == outcome)
    ].sort_values("date")

    if len(future) == 0:
        return None

    return future.iloc[0]["price"]

In [ ]:
large_buys = period_trades[
    (period_trades["side"] == "BUY") &
    (period_trades["outcome"] == "Yes") &
    (period_trades["size"] * period_trades["price"] >= 10000)
].copy()

large_buys["notional"] = (
    large_buys["size"] * large_buys["price"]
)

print("Крупных BUY:", len(large_buys))

In [ ]:
print("period_trades:", "period_trades" in globals())
print("trades_df:", "trades_df" in globals())
print("market:", "market" in globals())
print("markets_df:", "markets_df" in globals())

In [ ]:
import requests
import pandas as pd
import time

condition_id = "0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9"

url = "https://data-api.polymarket.com/v2/trades"

all_trades = []
cursor = None
page = 0

while True:
    params = {
        "condition": condition_id,
        "limit": 1000
    }

    if cursor:
        params["cursor"] = cursor

    response = requests.get(url, params=params)

    if response.status_code != 200:
        print("Ошибка API:", response.status_code)
        print(response.text)
        break

    data = response.json()

    trades = data.get("data", [])
    all_trades.extend(trades)

    page += 1
    print("Страница:", page, "| Сделок:", len(all_trades))

    cursor = data.get("pagination", {}).get("next_cursor")

    if not cursor:
        break

    time.sleep(0.2)

trades_df = pd.DataFrame(all_trades)

print("\nВсего сделок:", len(trades_df))

In [ ]:
trades_df["date"] = pd.to_datetime(
    trades_df["timestamp"],
    unit="s",
    utc=True
)

start_date = pd.Timestamp("2025-11-01", tz="UTC")
end_date = pd.Timestamp("2026-05-01", tz="UTC")

period_trades = trades_df[
    (trades_df["date"] >= start_date) &
    (trades_df["date"] < end_date)
].copy()

print("Сделок в исследуемом периоде:", len(period_trades))
print(
    "Период:",
    period_trades["date"].min(),
    "→",
    period_trades["date"].max()
)

In [ ]:
trades_df["date"] = pd.to_datetime(
    trades_df["timestamp"],
    unit="s",
    utc=True
)

start_date = pd.Timestamp("2025-11-01", tz="UTC")
end_date = pd.Timestamp("2026-05-01", tz="UTC")

period_trades = trades_df[
    (trades_df["date"] >= start_date) &
    (trades_df["date"] < end_date)
].copy()

print("Сделок в исследуемом периоде:", len(period_trades))
print(
    "Период:",
    period_trades["date"].min(),
    "→",
    period_trades["date"].max()
)

In [ ]:
trades_df["date"] = pd.to_datetime(
    trades_df["timestamp"],
    unit="s",
    utc=True
)

start_date = pd.Timestamp("2025-11-01", tz="UTC")
end_date = pd.Timestamp("2026-05-01", tz="UTC")

period_trades = trades_df[
    (trades_df["date"] >= start_date) &
    (trades_df["date"] < end_date)
].copy()

print("Trades in challenge period:", len(period_trades))
print("Unique wallets:", period_trades["proxyWallet"].nunique())

In [13]:
import requests
import pandas as pd
import time

condition_id = "0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9"

url = "https://data-api.polymarket.com/v2/trades"

all_trades = []
cursor = None
page = 0

while True:
    params = {
        "condition": condition_id,
        "limit": 1000
    }

    if cursor:
        params["cursor"] = cursor

    response = requests.get(url, params=params)

    if response.status_code != 200:
        print("Ошибка API:", response.status_code)
        print(response.text)
        break

    data = response.json()

    trades = data.get("data", [])
    all_trades.extend(trades)

    page += 1
    print("Страница:", page, "| Сделок:", len(all_trades))

    cursor = data.get("pagination", {}).get("next_cursor")

    if not cursor:
        break

    time.sleep(0.2)

trades_df = pd.DataFrame(all_trades)

print("\nВсего сделок:", len(trades_df))

Страница: 1 | Сделок: 1000
Страница: 2 | Сделок: 2000
Страница: 3 | Сделок: 3000
Страница: 4 | Сделок: 4000
Страница: 5 | Сделок: 5000
Страница: 6 | Сделок: 6000
Страница: 7 | Сделок: 7000
Страница: 8 | Сделок: 8000
Страница: 9 | Сделок: 9000
Страница: 10 | Сделок: 10000
Страница: 11 | Сделок: 11000
Страница: 12 | Сделок: 12000
Страница: 13 | Сделок: 13000
Страница: 14 | Сделок: 14000
Страница: 15 | Сделок: 15000
Страница: 16 | Сделок: 16000
Страница: 17 | Сделок: 17000
Страница: 18 | Сделок: 18000
Страница: 19 | Сделок: 19000
Страница: 20 | Сделок: 20000
Страница: 21 | Сделок: 21000
Страница: 22 | Сделок: 22000
Страница: 23 | Сделок: 23000
Страница: 24 | Сделок: 24000
Страница: 25 | Сделок: 25000
Страница: 26 | Сделок: 26000
Страница: 27 | Сделок: 27000
Страница: 28 | Сделок: 28000
Страница: 29 | Сделок: 29000
Страница: 30 | Сделок: 30000
Страница: 31 | Сделок: 31000
Страница: 32 | Сделок: 32000
Страница: 33 | Сделок: 33000
Страница: 34 | Сделок: 34000
Страница: 35 | Сделок: 35000
Страница: 36 | Сделок: 36000
Страница: 37 | Сделок: 37000
Страница: 38 | Сделок: 38000
Страница: 39 | Сделок: 39000
Страница: 40 | Сделок: 40000
Страница: 41 | Сделок: 41000
Страница: 42 | Сделок: 42000
Страница: 43 | Сделок: 43000
Страница: 44 | Сделок: 44000
Страница: 45 | Сделок: 45000
Страница: 46 | Сделок: 46000
Страница: 47 | Сделок: 47000
Страница: 48 | Сделок: 48000
Страница: 49 | Сделок: 49000
Страница: 50 | Сделок: 50000
Страница: 51 | Сделок: 51000
Страница: 52 | Сделок: 52000
Страница: 53 | Сделок: 53000
Страница: 54 | Сделок: 54000
Страница: 55 | Сделок: 55000
Страница: 56 | Сделок: 56000
Страница: 57 | Сделок: 57000
Страница: 58 | Сделок: 58000
Страница: 59 | Сделок: 59000
Страница: 60 | Сделок: 60000
Страница: 61 | Сделок: 61000
Страница: 62 | Сделок: 62000
Страница: 63 | Сделок: 63000
Страница: 64 | Сделок: 64000
Страница: 65 | Сделок: 65000
Страница: 66 | Сделок: 66000
Страница: 67 | Сделок: 67000
Страница: 68 | Сделок: 68000
Страница: 69 | Сделок: 69000
Страница: 70 | Сделок: 70000
Страница: 71 | Сделок: 71000
Страница: 72 | Сделок: 72000
Страница: 73 | Сделок: 73000
Страница: 74 | Сделок: 74000
Страница: 75 | Сделок: 75000
Страница: 76 | Сделок: 76000
Страница: 77 | Сделок: 77000
Страница: 78 | Сделок: 78000
Страница: 79 | Сделок: 79000
Страница: 80 | Сделок: 80000
Страница: 81 | Сделок: 81000
Страница: 82 | Сделок: 82000
Страница: 83 | Сделок: 83000
Страница: 84 | Сделок: 84000
Страница: 85 | Сделок: 85000
Страница: 86 | Сделок: 86000
Страница: 87 | Сделок: 87000
Страница: 88 | Сделок: 88000
Страница: 89 | Сделок: 89000
Страница: 90 | Сделок: 90000
Страница: 91 | Сделок: 91000
Страница: 92 | Сделок: 92000
Страница: 93 | Сделок: 93000
Страница: 94 | Сделок: 94000
Страница: 95 | Сделок: 95000
Страница: 96 | Сделок: 96000
Страница: 97 | Сделок: 97000
Страница: 98 | Сделок: 98000
Страница: 99 | Сделок: 99000
Страница: 100 | Сделок: 100000
Страница: 101 | Сделок: 101000
Страница: 102 | Сделок: 102000
Страница: 103 | Сделок: 103000
Страница: 104 | Сделок: 104000
Страница: 105 | Сделок: 105000
Страница: 106 | Сделок: 106000
Страница: 107 | Сделок: 107000
Страница: 108 | Сделок: 108000
Страница: 109 | Сделок: 109000
Страница: 110 | Сделок: 110000
Страница: 111 | Сделок: 111000
Страница: 112 | Сделок: 112000
Страница: 113 | Сделок: 113000
Страница: 114 | Сделок: 114000
Страница: 115 | Сделок: 115000
Страница: 116 | Сделок: 116000
Страница: 117 | Сделок: 117000
Страница: 118 | Сделок: 118000
Страница: 119 | Сделок: 119000
Страница: 120 | Сделок: 120000
Страница: 121 | Сделок: 121000
Страница: 122 | Сделок: 122000
Страница: 123 | Сделок: 123000
Страница: 124 | Сделок: 124000
Страница: 125 | Сделок: 125000
Страница: 126 | Сделок: 126000
Страница: 127 | Сделок: 127000
Страница: 128 | Сделок: 128000
Страница: 129 | Сделок: 129000
Страница: 130 | Сделок: 130000
Страница: 131 | Сделок: 131000
Страница: 132 | Сделок: 132000
Страница: 133 | Сделок: 133000
Страница: 134 | Сделок: 134000
Страница: 135 | Сделок: 135000
Страница: 136 | Сделок: 136000
Страница: 137 | Сделок: 137000
Страница: 138 | Сделок: 138000
Страница: 139 | Сделок: 139000
Страница: 140 | Сделок: 140000
Страница: 141 | Сделок: 141000
Страница: 142 | Сделок: 142000
Страница: 143 | Сделок: 143000
Страница: 144 | Сделок: 144000
Страница: 145 | Сделок: 145000
Страница: 146 | Сделок: 146000
Страница: 147 | Сделок: 147000
Страница: 148 | Сделок: 148000
Страница: 149 | Сделок: 149000
Страница: 150 | Сделок: 150000
Страница: 151 | Сделок: 151000
Страница: 152 | Сделок: 152000
Страница: 153 | Сделок: 153000
Страница: 154 | Сделок: 154000
Страница: 155 | Сделок: 155000
Страница: 156 | Сделок: 156000
Страница: 157 | Сделок: 157000
Страница: 158 | Сделок: 158000
Страница: 159 | Сделок: 159000
Страница: 160 | Сделок: 160000
Страница: 161 | Сделок: 161000
Страница: 162 | Сделок: 162000
Страница: 163 | Сделок: 163000
Страница: 164 | Сделок: 164000
Страница: 165 | Сделок: 165000
Страница: 166 | Сделок: 166000
Страница: 167 | Сделок: 167000
Страница: 168 | Сделок: 168000
Страница: 169 | Сделок: 169000
Страница: 170 | Сделок: 170000
Страница: 171 | Сделок: 171000
Страница: 172 | Сделок: 172000
Страница: 173 | Сделок: 173000
Страница: 174 | Сделок: 174000
Страница: 175 | Сделок: 175000
Страница: 176 | Сделок: 176000
Страница: 177 | Сделок: 177000
Страница: 178 | Сделок: 178000
Страница: 179 | Сделок: 179000
Страница: 180 | Сделок: 180000
Страница: 181 | Сделок: 181000
Страница: 182 | Сделок: 182000
Страница: 183 | Сделок: 183000
Страница: 184 | Сделок: 184000
Страница: 185 | Сделок: 185000
Страница: 186 | Сделок: 186000
Страница: 187 | Сделок: 187000
Страница: 188 | Сделок: 188000
Страница: 189 | Сделок: 189000
Страница: 190 | Сделок: 190000
Страница: 191 | Сделок: 191000
Страница: 192 | Сделок: 192000
Страница: 193 | Сделок: 193000
Страница: 194 | Сделок: 194000
Страница: 195 | Сделок: 195000
Страница: 196 | Сделок: 196000
Страница: 197 | Сделок: 197000
Страница: 198 | Сделок: 198000
Страница: 199 | Сделок: 199000
Страница: 200 | Сделок: 200000
Страница: 201 | Сделок: 201000
Страница: 202 | Сделок: 202000
Страница: 203 | Сделок: 203000
Страница: 204 | Сделок: 204000
Страница: 205 | Сделок: 205000
Страница: 206 | Сделок: 206000
Страница: 207 | Сделок: 207000
Страница: 208 | Сделок: 208000
Страница: 209 | Сделок: 209000
Страница: 210 | Сделок: 210000
Страница: 211 | Сделок: 211000
Страница: 212 | Сделок: 212000
Страница: 213 | Сделок: 213000
Страница: 214 | Сделок: 214000
Страница: 215 | Сделок: 215000
Страница: 216 | Сделок: 216000
Страница: 217 | Сделок: 217000
Страница: 218 | Сделок: 218000
Страница: 219 | Сделок: 219000
Страница: 220 | Сделок: 220000
Страница: 221 | Сделок: 221000
Страница: 222 | Сделок: 222000
Страница: 223 | Сделок: 223000
Страница: 224 | Сделок: 224000
Страница: 225 | Сделок: 225000
Страница: 226 | Сделок: 226000
Страница: 227 | Сделок: 227000
Страница: 228 | Сделок: 228000
Страница: 229 | Сделок: 229000
Страница: 230 | Сделок: 230000
Страница: 231 | Сделок: 231000
Страница: 232 | Сделок: 232000
Страница: 233 | Сделок: 233000
Страница: 234 | Сделок: 234000
Страница: 235 | Сделок: 235000
Страница: 236 | Сделок: 236000
Страница: 237 | Сделок: 237000
Страница: 238 | Сделок: 238000
Страница: 239 | Сделок: 239000
Страница: 240 | Сделок: 240000
Страница: 241 | Сделок: 240993

Всего сделок: 240993

In [14]:
start_date = pd.Timestamp("2025-11-01", tz="UTC")
end_date = pd.Timestamp("2026-05-01", tz="UTC")

trades_df["date"] = pd.to_datetime(
    trades_df["timestamp"],
    unit="s",
    utc=True
)

period_trades = trades_df[
    (trades_df["date"] >= start_date) &
    (trades_df["date"] < end_date)
].copy()

print("Trades:", len(period_trades))
print("Wallets:", period_trades["proxyWallet"].nunique())

Trades: 37808

KeyError: 'proxyWallet'

In [15]:
print(trades_df.columns.tolist())

['proxy_wallet', 'side', 'token_id', 'condition_id', 'size', 'price', 'timestamp', 'title', 'slug', 'icon', 'event_slug', 'outcome', 'outcome_index', 'name', 'pseudonym', 'bio', 'profile_image', 'profile_image_optimized', 'transaction_hash', 'date']

In [16]:
print("Trades:", len(period_trades))
print("Wallets:", period_trades["proxy_wallet"].nunique())

Trades: 37808
Wallets: 12911

In [17]:
period_trades["notional"] = (
    period_trades["size"] * period_trades["price"]
)

wallet_stats = (
    period_trades
    .groupby("proxy_wallet")
    .agg(
        trades=("proxy_wallet", "size"),
        notional=("notional", "sum"),
        avg_trade=("notional", "mean"),
        max_trade=("notional", "max")
    )
    .reset_index()
    .sort_values("notional", ascending=False)
)

wallet_stats.head(10)

,proxy_wallet,trades,notional,avg_trade,max_trade
3416,0x448861155279dbf833d041b963e3ac854599e319,24,529020.923928,22042.538497,121103.071957
11870,0xeac3f7345a02cbeefa921caab22062a5574f8a6c,42,525457.665118,12510.896789,21099.999985
5166,0x67b62ef7678b34e0a5c6242932ac53bc775c2216,161,490974.695092,3049.532268,3285.696000
1867,0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1,45,418569.584558,9301.546324,99900.000000
6333,0x7e30c3a56d89edac738d788dd218a9e64fb91e50,4,379386.197258,94846.549315,159520.000000
11330,0xe0ac9addc56c19e771a0524f5d172af4d7a476ff,2,347262.169391,173631.084696,178262.169390
7542,0x9604b357e8307b0ccc8eb5812725d2b112c6fc1d,2,338897.561718,169448.780859,275494.858671
5927,0x7702028f87deda0ceefea619209ece9630669791,9,335472.705118,37274.745013,185616.113820
8711,0xac2474546159e1349c57514d879732793db3941c,4,314585.990752,78646.497688,185283.480420
12398,0xf5d92058c977a9c957c6cbfbe3e9a27c83a9be50,24,308182.080863,12840.920036,54093.000000

In [18]:
resolution_time = pd.Timestamp(
    "2025-11-05T05:44:47Z"
)

period_trades["hours_to_resolution"] = (
    (resolution_time - period_trades["date"])
    .dt.total_seconds() / 3600
)

print(
    period_trades[
        ["date", "side", "outcome", "price", "notional", "hours_to_resolution"]
    ].head()
)

                       date  side outcome  price    notional  \
0 2025-11-05 05:45:05+00:00  SELL     Yes  0.999    78.46146
1 2025-11-05 05:44:47+00:00  SELL     Yes  0.999     1.17882
2 2025-11-05 05:44:19+00:00  SELL     Yes  0.999  9972.01800
3 2025-11-05 05:43:57+00:00  SELL     Yes  0.999   191.78802
4 2025-11-05 05:43:43+00:00  SELL     Yes  0.999   280.71900

   hours_to_resolution
0            -0.005000
1             0.000000
2             0.007778
3             0.013889
4             0.017778

In [19]:
candidates = period_trades[
    (period_trades["side"] == "BUY") &
    (period_trades["outcome"] == "Yes") &
    (period_trades["hours_to_resolution"] >= 6) &
    (period_trades["hours_to_resolution"] <= 48) &
    (period_trades["price"] < 0.90)
].copy()

print("Candidate trades:", len(candidates))
print("Candidate wallets:", candidates["proxy_wallet"].nunique())

Candidate trades: 647
Candidate wallets: 462

In [20]:
candidate_wallets = (
    candidates
    .groupby("proxy_wallet")
    .agg(
        candidate_trades=("proxy_wallet", "size"),
        candidate_notional=("notional", "sum"),
        max_trade=("notional", "max"),
        avg_price=("price", "mean"),
        earliest_entry=("date", "min")
    )
    .reset_index()
    .sort_values("candidate_notional", ascending=False)
)

candidate_wallets.head(15)

,proxy_wallet,candidate_trades,candidate_notional,max_trade,avg_price,earliest_entry
307,0xac80edc92b47b90fef0b8283b7c1f8bc87f197b1,1,26803.237500,26803.237500,0.894000,2025-11-04 05:22:45+00:00
27,0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8,4,17408.315080,7383.057660,0.891250,2025-11-04 05:31:03+00:00
22,0x1117eade222413335b7ec959e5b48c1d3dbc3532,4,16379.168560,7345.318400,0.896000,2025-11-04 04:22:01+00:00
125,0x4630c2b76857c6fd31743c8fdf520a4ef49938c8,1,14994.519997,14994.519997,0.896000,2025-11-04 04:07:43+00:00
355,0xc8b0c7331a0c879a033003d81501f51b318f6815,3,13362.589991,9999.999992,0.895000,2025-11-04 04:31:35+00:00
201,0x7177a7f5c216809c577c50c77b12aae81f81ddef,1,11375.616000,11375.616000,0.896000,2025-11-04 04:11:17+00:00
361,0xccdda67a0cd3dde9e15379cdf87c36c9172e516c,1,9972.949997,9972.949997,0.900000,2025-11-04 03:57:37+00:00
295,0xa6c8c6cd8c0e0dbdfbb02d2ce1332bd3acf8cd53,5,9640.424260,4709.969760,0.894985,2025-11-04 05:18:13+00:00
162,0x614dc8d3542c12103d2c6a3553fd761e391d1546,1,8930.000000,8930.000000,0.893000,2025-11-04 06:03:21+00:00
449,0xfcf2378f20cf408d077c21e731272f21cccea469,7,8522.429980,1799.999998,0.880945,2025-11-04 03:56:21+00:00
298,0xa849228d5664e59f2b397b68f0429ab10668c825,8,8144.499090,2038.450000,0.894749,2025-11-04 03:59:45+00:00
373,0xd3394d85e1c3f2990e348d1432eed4c781b1d3a1,1,7999.999994,7999.999994,0.892140,2025-11-04 05:52:03+00:00
128,0x48ae7a7e3f67853fee0d505f32ebbfc6d47f4683,1,5576.039994,5576.039994,0.898843,2025-11-04 04:22:43+00:00
185,0x6a769bf6bd6a991d54f5a97f0c45ff6164e42890,1,4981.989999,4981.989999,0.897000,2025-11-04 04:18:27+00:00
108,0x3d64dc76cfb30f5c668284886a9bfc505a9901fa,1,4933.500000,4933.500000,0.897000,2025-11-04 04:12:55+00:00

In [22]:
def price_after_hours(trades, buy_time, hours, outcome):
    target_time = buy_time + pd.Timedelta(hours=hours)

    future = trades[
        (trades["date"] >= target_time) &
        (trades["outcome"] == outcome)
    ].sort_values("date")

    if len(future) == 0:
        return None

    return future.iloc[0]["price"]

In [23]:
candidates["price_6h"] = candidates.apply(
    lambda row: price_after_hours(
        period_trades,
        row["date"],
        6,
        row["outcome"]
    ),
    axis=1
)

candidates["move_6h"] = (
    candidates["price_6h"] - candidates["price"]
)

print("Calculated:", candidates["price_6h"].notna().sum())

Calculated: 647

In [24]:
candidates[
    [
        "proxy_wallet",
        "date",
        "price",
        "price_6h",
        "move_6h",
        "notional",
        "hours_to_resolution"
    ]
].sort_values(
    "move_6h",
    ascending=False
).head(15)

,proxy_wallet,date,price,price_6h,move_6h,notional,hours_to_resolution
14184,0xfcf2378f20cf408d077c21e731272f21cccea469,2025-11-04 04:59:25+00:00,0.874000,0.922000,0.048000,136.069994,24.756111
14186,0x15d41bb2639a043060ef5132c77ce2784fef6ddd,2025-11-04 04:59:21+00:00,0.874000,0.922000,0.048000,14.858000,24.757222
14185,0xfcf2378f20cf408d077c21e731272f21cccea469,2025-11-04 04:59:23+00:00,0.874000,0.922000,0.048000,131.100000,24.756667
14183,0x39d0f1dca6fb7e5514858c1a337724a426764fe8,2025-11-04 04:59:31+00:00,0.874000,0.922000,0.048000,13.110000,24.754444
14187,0xdebbe89ceb32828a99648bca497684f5209ceedb,2025-11-04 04:59:21+00:00,0.874000,0.922000,0.048000,852.150000,24.757222
14179,0xfcf2378f20cf408d077c21e731272f21cccea469,2025-11-04 04:59:53+00:00,0.880000,0.922000,0.042000,1799.999998,24.748333
14180,0xfcf2378f20cf408d077c21e731272f21cccea469,2025-11-04 04:59:53+00:00,0.880000,0.922000,0.042000,1799.999998,24.748333
14177,0xfcf2378f20cf408d077c21e731272f21cccea469,2025-11-04 04:59:57+00:00,0.879619,0.921000,0.041381,1799.219998,24.747222
14176,0xfcf2378f20cf408d077c21e731272f21cccea469,2025-11-04 04:59:57+00:00,0.880000,0.921000,0.041000,1799.219998,24.747222
14175,0xeec50edede5d961efb02e20bfd3275dd1e7fb6fe,2025-11-04 04:59:57+00:00,0.880000,0.921000,0.041000,488.637600,24.747222
14178,0x09fe78c8b9f10fb9c7c0a584bfab4205c76876ee,2025-11-04 04:59:57+00:00,0.880000,0.921000,0.041000,14.916000,24.747222
14150,0xdebbe89ceb32828a99648bca497684f5209ceedb,2025-11-04 05:02:57+00:00,0.882000,0.923000,0.041000,110.250000,24.697222
14242,0x2377b3c630c033796dceb21d98270036fdbbd92a,2025-11-04 04:54:41+00:00,0.885000,0.924000,0.039000,45.135000,24.835000
14243,0x4fbe162b6e54ad8fb4ba739df9d7f5fbc90f7db9,2025-11-04 04:54:41+00:00,0.885000,0.924000,0.039000,8.850000,24.835000
14068,0xa65ad8b45cd368353a55f4bd974c33325eb61a92,2025-11-04 05:11:47+00:00,0.884000,0.922601,0.038601,6.159998,24.550000

In [25]:
wallet_signal = (
    candidates
    .groupby("proxy_wallet")
    .agg(
        trades=("proxy_wallet", "size"),
        notional=("notional", "sum"),
        avg_entry=("price", "mean"),
        avg_move_6h=("move_6h", "mean"),
        max_move_6h=("move_6h", "max"),
        earliest_entry=("date", "min")
    )
    .reset_index()
)

wallet_signal = wallet_signal.sort_values(
    ["avg_move_6h", "notional"],
    ascending=[False, False]
)

wallet_signal.head(20)

,proxy_wallet,trades,notional,avg_entry,avg_move_6h,max_move_6h,earliest_entry
14,0x09fe78c8b9f10fb9c7c0a584bfab4205c76876ee,1,14.916000,0.880000,0.041000,0.041000,2025-11-04 04:59:57+00:00
449,0xfcf2378f20cf408d077c21e731272f21cccea469,7,8522.429980,0.880945,0.040341,0.048000,2025-11-04 03:56:21+00:00
59,0x2377b3c630c033796dceb21d98270036fdbbd92a,1,45.135000,0.885000,0.039000,0.039000,2025-11-04 04:54:41+00:00
138,0x4fbe162b6e54ad8fb4ba739df9d7f5fbc90f7db9,1,8.850000,0.885000,0.039000,0.039000,2025-11-04 04:54:41+00:00
292,0xa65ad8b45cd368353a55f4bd974c33325eb61a92,1,6.159998,0.884000,0.038601,0.038601,2025-11-04 05:11:47+00:00
290,0xa4651fbe325887ed9c10bee69de8758e2fa4537b,1,2.000000,0.885000,0.038000,0.038000,2025-11-04 04:56:51+00:00
435,0xf1ebd4ca556abf4ceb99995a75cd2d2325ea7afe,1,44.250000,0.885000,0.038000,0.038000,2025-11-04 04:55:45+00:00
102,0x3abafd5289b6e970d0a7413d0aef102ece779cd5,2,9.292000,0.884500,0.038000,0.038000,2025-11-04 04:55:29+00:00
350,0xc654fb6982c289d431b78cbd9c49477f0556e657,1,889.416150,0.885000,0.038000,0.038000,2025-11-04 05:11:19+00:00
431,0xf010fb4a7b6438de6228ecdc5d4d293c1aa617fa,1,17.694000,0.884700,0.037300,0.037300,2025-11-04 05:00:31+00:00
395,0xdebbe89ceb32828a99648bca497684f5209ceedb,5,1505.670000,0.883000,0.037200,0.048000,2025-11-04 04:59:21+00:00
245,0x8d05e0092874454a2166ccf7d953fd11d1f8edb1,1,3.999998,0.886000,0.037000,0.037000,2025-11-04 05:10:57+00:00
157,0x5f6a5be8dbf725bf5b064a36c6a68684da4f16fa,1,4.999996,0.885000,0.037000,0.037000,2025-11-04 05:06:15+00:00
103,0x3b5145681c74fd8e37d47c4a082304aa535d87da,1,2.799999,0.887000,0.036324,0.036324,2025-11-04 04:56:07+00:00
179,0x673e7271301f2bba0bb32c33f181c351a659e66a,1,129.999999,0.885877,0.036123,0.036123,2025-11-04 05:12:05+00:00
226,0x83b04c2e27b64998031ed86dafeb00e288c93c6c,1,3.999993,0.887000,0.036000,0.036000,2025-11-04 05:07:33+00:00
222,0x815ed550fe90875e34c05d79aff9c5df8d06d0c3,1,9.999994,0.886000,0.036000,0.036000,2025-11-04 05:09:49+00:00
250,0x8fc3e35d0f5f1682dbf4677c288bba72ce8186de,1,99.939999,0.886000,0.036000,0.036000,2025-11-04 05:00:39+00:00
441,0xf94834a269deff06ca2594aebfb5a4f0e98bfb0b,1,131.009994,0.887000,0.036000,0.036000,2025-11-04 05:07:33+00:00
401,0xe2314b08a84feff5787d6a7b7984b7e334ef4e3e,1,491.953800,0.885000,0.036000,0.036000,2025-11-04 04:56:59+00:00

In [27]:
strong_wallets = wallet_signal[
    wallet_signal["notional"] >= 500
].copy()

print("Wallets:", len(strong_wallets))

strong_wallets[
    [
        "proxy_wallet",
        "trades",
        "notional",
        "avg_entry",
        "avg_move_6h",
        "max_move_6h"
    ]
].sort_values(
    "avg_move_6h",
    ascending=False
).head(20)

Wallets: 91

,proxy_wallet,trades,notional,avg_entry,avg_move_6h,max_move_6h
449,0xfcf2378f20cf408d077c21e731272f21cccea469,7,8522.429980,0.880945,0.040341,0.048000
350,0xc654fb6982c289d431b78cbd9c49477f0556e657,1,889.416150,0.885000,0.038000,0.038000
395,0xdebbe89ceb32828a99648bca497684f5209ceedb,5,1505.670000,0.883000,0.037200,0.048000
287,0xa3922eaac3633b419f1d30831511275d0a941415,2,3002.541070,0.885663,0.035837,0.037674
218,0x7ebbb7590915dc9549b4deb29ff46546c0ee017a,1,743.409998,0.887875,0.035125,0.035125
343,0xc0eea70081e176f3548b409742d6e361c0fdec14,1,888.562420,0.888562,0.034438,0.034438
342,0xc02147dee42356b7a4edbb1c35ac4ffa95f61fa8,1,1076.019600,0.887842,0.034158,0.034158
276,0x9c1e315c39bb572fb56ce46c88394bd1abc70cd2,2,2999.999997,0.888492,0.033970,0.034000
285,0xa1ed2ae1eaaa057b6d09204cbb0808ef78a4e774,1,1999.999993,0.888733,0.033267,0.033267
426,0xeec50edede5d961efb02e20bfd3275dd1e7fb6fe,3,519.912600,0.886667,0.033000,0.041000
452,0xfde8c6c089bc4cca2f0b77dbe775cec92839c52f,5,2213.359993,0.889506,0.029694,0.036000
220,0x805918d96ce57839551418e80bb31bc48ec21b5f,4,3572.098000,0.893024,0.029475,0.037902
39,0x17fe0744eae5fb488527370fb63b466566059d84,1,1000.832000,0.896000,0.029000,0.029000
440,0xf901d65a6337a7a918c004e16098447dcad97aa1,1,993.511680,0.896000,0.028378,0.028378
283,0xa1ad12f75191bf1129651b3bd82df6345dced1b2,1,933.229998,0.895996,0.028004,0.028004
414,0xe87976e1960f7a395dcd4b82d202e91ce0578714,4,3225.701640,0.895750,0.027250,0.030000
273,0x9a9841f6add86f38c1d6b602a46fa752e3a59b57,3,2099.999990,0.891665,0.026668,0.033000
156,0x5ef16be18a2b9af7e9f2e6f0f0d3c7c129c3db7e,1,1000.832000,0.896000,0.026000,0.026000
34,0x15d41bb2639a043060ef5132c77ce2784fef6ddd,41,2291.879000,0.893317,0.025635,0.048000
48,0x1ce50c72dbe605ca98bf054df958c6fdf4b9a686,2,1211.657240,0.892000,0.025500,0.026000

In [28]:
strong_wallets["signal_value"] = (
    strong_wallets["notional"] * strong_wallets["avg_move_6h"]
)

strong_wallets.sort_values(
    "signal_value",
    ascending=False
)[
    [
        "proxy_wallet",
        "trades",
        "notional",
        "avg_entry",
        "avg_move_6h",
        "signal_value"
    ]
].head(20)

,proxy_wallet,trades,notional,avg_entry,avg_move_6h,signal_value
307,0xac80edc92b47b90fef0b8283b7c1f8bc87f197b1,1,26803.237500,0.894000,0.016000,428.851800
22,0x1117eade222413335b7ec959e5b48c1d3dbc3532,4,16379.168560,0.896000,0.023445,384.002292
27,0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8,4,17408.315080,0.891250,0.021500,374.278759
449,0xfcf2378f20cf408d077c21e731272f21cccea469,7,8522.429980,0.880945,0.040341,343.804043
355,0xc8b0c7331a0c879a033003d81501f51b318f6815,3,13362.589991,0.895000,0.024943,333.307465
125,0x4630c2b76857c6fd31743c8fdf520a4ef49938c8,1,14994.519997,0.896000,0.022000,329.879441
201,0x7177a7f5c216809c577c50c77b12aae81f81ddef,1,11375.616000,0.896000,0.023000,261.638951
162,0x614dc8d3542c12103d2c6a3553fd761e391d1546,1,8930.000000,0.893000,0.024978,223.050231
373,0xd3394d85e1c3f2990e348d1432eed4c781b1d3a1,1,7999.999994,0.892140,0.024860,198.878934
298,0xa849228d5664e59f2b397b68f0429ab10668c825,8,8144.499090,0.894749,0.023927,194.874275
361,0xccdda67a0cd3dde9e15379cdf87c36c9172e516c,1,9972.949997,0.900000,0.018000,179.513101
295,0xa6c8c6cd8c0e0dbdfbb02d2ce1332bd3acf8cd53,5,9640.424260,0.894985,0.015605,150.440051
185,0x6a769bf6bd6a991d54f5a97f0c45ff6164e42890,1,4981.989999,0.897000,0.023000,114.585767
128,0x48ae7a7e3f67853fee0d505f32ebbfc6d47f4683,1,5576.039994,0.898843,0.020157,112.394803
108,0x3d64dc76cfb30f5c668284886a9bfc505a9901fa,1,4933.500000,0.897000,0.022000,108.537000
287,0xa3922eaac3633b419f1d30831511275d0a941415,2,3002.541070,0.885663,0.035837,107.602644
107,0x3c918a8ef8c379304f744592120cbb4d76149af7,1,4475.000000,0.895000,0.024000,107.400000
220,0x805918d96ce57839551418e80bb31bc48ec21b5f,4,3572.098000,0.893024,0.029475,105.288829
276,0x9c1e315c39bb572fb56ce46c88394bd1abc70cd2,2,2999.999997,0.888492,0.033970,101.910077
38,0x17ce7c9a7f768bfa98946caf7d64c9e051f5beec,2,3995.838990,0.897000,0.023000,91.904280

In [29]:
timing = (
    candidates
    .groupby("proxy_wallet")
    .agg(
        avg_hours_to_resolution=("hours_to_resolution", "mean"),
        min_hours_to_resolution=("hours_to_resolution", "min")
    )
    .reset_index()
)

strong_wallets = strong_wallets.merge(
    timing,
    on="proxy_wallet",
    how="left"
)

strong_wallets[
    [
        "proxy_wallet",
        "trades",
        "notional",
        "avg_move_6h",
        "signal_value",
        "avg_hours_to_resolution"
    ]
].sort_values(
    "signal_value",
    ascending=False
).head(15)

,proxy_wallet,trades,notional,avg_move_6h,signal_value,avg_hours_to_resolution
86,0xac80edc92b47b90fef0b8283b7c1f8bc87f197b1,1,26803.237500,0.016000,428.851800,24.367222
42,0x1117eade222413335b7ec959e5b48c1d3dbc3532,4,16379.168560,0.023445,384.002292,25.294583
66,0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8,4,17408.315080,0.021500,374.278759,24.064583
0,0xfcf2378f20cf408d077c21e731272f21cccea469,7,8522.429980,0.040341,343.804043,24.901587
27,0xc8b0c7331a0c879a033003d81501f51b318f6815,3,13362.589991,0.024943,333.307465,24.777037
57,0x4630c2b76857c6fd31743c8fdf520a4ef49938c8,1,14994.519997,0.022000,329.879441,25.617778
50,0x7177a7f5c216809c577c50c77b12aae81f81ddef,1,11375.616000,0.023000,261.638951,25.558333
26,0x614dc8d3542c12103d2c6a3553fd761e391d1546,1,8930.000000,0.024978,223.050231,23.690556
28,0xd3394d85e1c3f2990e348d1432eed4c781b1d3a1,1,7999.999994,0.024860,198.878934,23.878889
40,0xa849228d5664e59f2b397b68f0429ab10668c825,8,8144.499090,0.023927,194.874275,24.921667
83,0xccdda67a0cd3dde9e15379cdf87c36c9172e516c,1,9972.949997,0.018000,179.513101,25.786111
88,0xa6c8c6cd8c0e0dbdfbb02d2ce1332bd3acf8cd53,5,9640.424260,0.015605,150.440051,24.414889
47,0x6a769bf6bd6a991d54f5a97f0c45ff6164e42890,1,4981.989999,0.023000,114.585767,25.438889
73,0x48ae7a7e3f67853fee0d505f32ebbfc6d47f4683,1,5576.039994,0.020157,112.394803,25.367778
58,0x3d64dc76cfb30f5c668284886a9bfc505a9901fa,1,4933.500000,0.022000,108.537000,25.531111

In [30]:
wallet = "0xac80edc92b47b90fef0b8283b7c1f8bc87f197b1"

wallet_history = period_trades[
    period_trades["proxy_wallet"] == wallet
].copy()

wallet_history[
    [
        "date",
        "side",
        "outcome",
        "price",
        "size",
        "notional",
        "hours_to_resolution"
    ]
].sort_values("date")

,date,side,outcome,price,size,notional,hours_to_resolution
13969,2025-11-04 05:22:45+00:00,BUY,Yes,0.894,29981.25,26803.2375,24.367222

In [31]:
[x for x in globals() if "market" in x.lower()]

['markets', 'markets_df', 'all_markets', 'valid_markets']

In [32]:
print("markets:", len(markets))
print("markets_df:", len(markets_df))
print("all_markets:", len(all_markets))
print("valid_markets:", len(valid_markets))

markets: 2
markets_df: 2100
all_markets: 2102
valid_markets: 2100

In [33]:
print(markets_df.columns.tolist())

['id', 'question', 'conditionId', 'slug', 'resolutionSource', 'endDate', 'startDate', 'image', 'icon', 'description', 'outcomes', 'outcomePrices', 'volume', 'active', 'closed', 'marketMakerAddress', 'createdAt', 'updatedAt', 'closedTime', 'new', 'featured', 'submitted_by', 'archived', 'resolvedBy', 'restricted', 'groupItemTitle', 'groupItemThreshold', 'questionID', 'umaEndDate', 'enableOrderBook', 'orderPriceMinTickSize', 'orderMinSize', 'umaResolutionStatus', 'volumeNum', 'endDateIso', 'startDateIso', 'hasReviewedDates', 'volume1wk', 'volume1mo', 'volume1yr', 'clobTokenIds', 'comboStatus', 'umaBond', 'umaReward', 'volume1wkAmm', 'volume1moAmm', 'volume1yrAmm', 'volume1wkClob', 'volume1moClob', 'volume1yrClob', 'volumeClob', 'acceptingOrders', 'negRisk', 'events', 'ready', 'funded', 'acceptingOrdersTimestamp', 'cyom', 'approved', 'clobRewards', 'rewardsMinSize', 'rewardsMaxSpread', 'spread', 'automaticallyResolved', 'oneDayPriceChange', 'oneHourPriceChange', 'oneWeekPriceChange', 'oneMonthPriceChange', 'oneYearPriceChange', 'lastTradePrice', 'bestAsk', 'automaticallyActive', 'clearBookOnStart', 'manualActivation', 'negRiskOther', 'umaResolutionStatuses', 'pendingDeployment', 'deploying', 'rfqEnabled', 'holdingRewardsEnabled', 'feesEnabled', 'feeType', 'version', 'bestBid', 'gameStartTime', 'customLiveness', 'seriesColor', 'showGmpSeries', 'showGmpOutcome', 'negRiskMarketID', 'negRiskRequestID', 'liquidity', 'liquidityNum', 'liquidityAmm', 'liquidityClob', 'competitive', 'makerBaseFee', 'takerBaseFee', 'feeSchedule', 'deployingTimestamp']

In [34]:
top30 = (
    markets_df
    .sort_values("volumeNum", ascending=False)
    .head(30)
    [["question", "conditionId", "volumeNum", "closedTime"]]
    .reset_index(drop=True)
)

top30

,question,conditionId,volumeNum,closedTime
0,Will Zohran Mamdani win the 2025 NYC mayoral e...,0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed...,1.432549e+08,2025-11-05 05:44:47+00
1,Will Frances Fitzgerald win the Irish Presiden...,0x4037ced85ebd734a30727e948abfe77b19fc2ce7ee05...,1.150672e+08,2025-10-25 21:53:33+00
2,Will Hunor Kelemen win the Romanian presidenti...,0x784d67eb3b205e7f6543b09d8737d5dc1c2a14d43a10...,8.089710e+07,2025-05-19 05:38:37+00
3,Russia x Ukraine ceasefire in 2025?,0x8ee2f1640386310eb5e7ffa596ba9335f2d324e303d2...,7.375299e+07,2026-01-01 07:18:23+00
4,Will the Tennessee Titans win Super Bowl 2026?,0xf2d034812c1e871421eb6ca9afd30f2a03f0494fc910...,7.084816e+07,2025-12-01 01:03:10+00
5,Will the Miami Dolphins win Super Bowl 2026?,0xb222caecba4942b88a87adc145f1c27eb822e6fa2d23...,6.408620e+07,2025-12-16 07:33:47+00
6,Will Curtis Sliwa win the 2025 NYC mayoral ele...,0xd7bd58d09efa1ff15be61cf30587e79444971ab125d5...,6.040205e+07,2025-11-05 06:13:17+00
7,Will the Carolina Panthers win Super Bowl 2026?,0xb232c915770ea41eb3ec3dbb2c7209c7277592373838...,6.023645e+07,2026-01-11 04:18:46+00
8,Will the New York Jets win Super Bowl 2026?,0xd8d889f4c49f58d98538d08182a07c27206f0e98f9f0...,5.723207e+07,2025-12-08 01:03:11+00
9,Will the Cleveland Browns win Super Bowl 2026?,0x8f0f5125028c535d93f548225a4a2479a03793a49705...,5.137560e+07,2025-12-08 01:12:59+00
10,Will Nicușor Dan win the Romanian presidential...,0xaf51603d78545c838490bafe178ee9ff4c23d0c2161f...,5.099100e+07,2025-05-19 04:09:33+00
11,Will the Las Vegas Raiders win Super Bowl 2026?,0xd28f9dfab98d6b2a8a22d8ff7e8d109678fc8275710b...,5.024211e+07,2025-12-01 03:44:10+00
12,Will Jim Walden win the 2025 NYC mayoral elect...,0x9e56a92abcf4996105ab15ce5612742bc33f4b9097bb...,4.920758e+07,2025-11-05 06:14:21+00
13,Will Andrew Cuomo win the 2025 NYC mayoral ele...,0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b39373...,4.875594e+07,2025-11-05 05:56:23+00
14,Will the New Orleans Saints win Super Bowl 2026?,0x184228c1bfc9502d38f6f9984667f3da7b2f955616f1...,4.828319e+07,2025-12-01 01:01:14+00
15,Will the Arizona Cardinals win Super Bowl 2026?,0xc319ae3e39f6a0b441fd02d37058ee8af4133967a205...,4.204800e+07,2025-12-01 00:41:18+00
16,Will the Cincinnati Bengals win Super Bowl 2026?,0x580ffec1f7b057910f9f596c80d203870f3028b04784...,3.999804e+07,2025-12-15 00:50:37+00
17,Will the New York Giants win Super Bowl 2026?,0xf9915c09cfdb45b8ba1335620c1da05d12913ad1d43b...,3.749100e+07,2025-11-24 02:43:05+00
18,Maduro out in 2025?,0xafc235557ace53ff0b0d2e93392314a7c3f3daab26a7...,3.464140e+07,2026-01-01 08:30:59+00
19,Will George Simion win the Romanian presidenti...,0x5fc28bfcb6f16080415695b53f1f60820f403a94ce16...,3.179689e+07,2025-05-19 02:59:19+00
20,"Will Bitcoin reach $1,000,000 by December 31, ...",0xd8b9ff369452daebce1ac8cb6a29d6817903e8516835...,3.139461e+07,2026-01-01 07:20:31+00
21,Will Donald Trump win Nobel Peace Prize in 2025?,0xab6faa3e66abacc484bbb4bd31ae5e2a56d6f6252b50...,2.984720e+07,2025-10-10 11:03:16+00
22,Will George Russell be the 2025 Drivers Champion?,0x7e8953cc66f9dabfe80fb0d1a9284bffb7a293f700b2...,2.969811e+07,2025-11-10 06:35:19+00
23,Will Brad Lander win the 2025 NYC mayoral elec...,0x34c989bada239153e86a009b3d25539db4c86fc4df3e...,2.924689e+07,2025-11-05 06:13:17+00
24,Will Saudi Aramco be the largest company in th...,0xb1a6136ad23d19526c4929d2e79c79e999628de931ca...,2.524078e+07,2026-01-01 01:11:43+00
25,Will Eric Adams win the 2025 NYC mayoral elect...,0x846ce700a217ec7b75b8d078450f7e88eb5f44c76c12...,2.449801e+07,2025-11-05 06:12:19+00
26,Will Lewis Hamilton be the 2025 Drivers Champion?,0x9c60e608e40b658cf15c18b0aaaddda7c6614e66187e...,2.054660e+07,2025-09-21 19:46:02+00
27,Will Octavian Berceanu be the next Mayor of Bu...,0x2017c048aeee624d3597ffd0c2273a0e2c2aec4dfb89...,2.030469e+07,2025-12-08 04:23:11+00
28,Will Zellnor Myrie win the 2025 NYC mayoral el...,0xcdec3de1f9c73e9ade1d33dde14b96e7241d0cc87f04...,1.938366e+07,2025-11-05 06:13:17+00
29,"Will Bitcoin reach $200,000 by December 31, 2025?",0x4e2887e913cd6e091c9b07b5e4013b24f372453efa6f...,1.927571e+07,2026-01-01 07:16:21+00

In [36]:
closed = pd.to_datetime(
    markets_df["closedTime"],
    utc=True,
    format="mixed"
)

period_markets = markets_df[
    (closed >= pd.Timestamp("2025-11-01", tz="UTC")) &
    (closed < pd.Timestamp("2026-05-01", tz="UTC"))
].copy()

top30 = (
    period_markets
    .sort_values("volumeNum", ascending=False)
    .head(30)
    [["question", "conditionId", "volumeNum", "closedTime"]]
    .reset_index(drop=True)
)

print("Markets in period:", len(period_markets))
top30

Markets in period: 1161

,question,conditionId,volumeNum,closedTime
0,Will Zohran Mamdani win the 2025 NYC mayoral e...,0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed...,1.432549e+08,2025-11-05 05:44:47+00
1,Russia x Ukraine ceasefire in 2025?,0x8ee2f1640386310eb5e7ffa596ba9335f2d324e303d2...,7.375299e+07,2026-01-01 07:18:23+00
2,Will the Tennessee Titans win Super Bowl 2026?,0xf2d034812c1e871421eb6ca9afd30f2a03f0494fc910...,7.084816e+07,2025-12-01 01:03:10+00
3,Will the Miami Dolphins win Super Bowl 2026?,0xb222caecba4942b88a87adc145f1c27eb822e6fa2d23...,6.408620e+07,2025-12-16 07:33:47+00
4,Will Curtis Sliwa win the 2025 NYC mayoral ele...,0xd7bd58d09efa1ff15be61cf30587e79444971ab125d5...,6.040205e+07,2025-11-05 06:13:17+00
5,Will the Carolina Panthers win Super Bowl 2026?,0xb232c915770ea41eb3ec3dbb2c7209c7277592373838...,6.023645e+07,2026-01-11 04:18:46+00
6,Will the New York Jets win Super Bowl 2026?,0xd8d889f4c49f58d98538d08182a07c27206f0e98f9f0...,5.723207e+07,2025-12-08 01:03:11+00
7,Will the Cleveland Browns win Super Bowl 2026?,0x8f0f5125028c535d93f548225a4a2479a03793a49705...,5.137560e+07,2025-12-08 01:12:59+00
8,Will the Las Vegas Raiders win Super Bowl 2026?,0xd28f9dfab98d6b2a8a22d8ff7e8d109678fc8275710b...,5.024211e+07,2025-12-01 03:44:10+00
9,Will Jim Walden win the 2025 NYC mayoral elect...,0x9e56a92abcf4996105ab15ce5612742bc33f4b9097bb...,4.920758e+07,2025-11-05 06:14:21+00
10,Will Andrew Cuomo win the 2025 NYC mayoral ele...,0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b39373...,4.875594e+07,2025-11-05 05:56:23+00
11,Will the New Orleans Saints win Super Bowl 2026?,0x184228c1bfc9502d38f6f9984667f3da7b2f955616f1...,4.828319e+07,2025-12-01 01:01:14+00
12,Will the Arizona Cardinals win Super Bowl 2026?,0xc319ae3e39f6a0b441fd02d37058ee8af4133967a205...,4.204800e+07,2025-12-01 00:41:18+00
13,Will the Cincinnati Bengals win Super Bowl 2026?,0x580ffec1f7b057910f9f596c80d203870f3028b04784...,3.999804e+07,2025-12-15 00:50:37+00
14,Will the New York Giants win Super Bowl 2026?,0xf9915c09cfdb45b8ba1335620c1da05d12913ad1d43b...,3.749100e+07,2025-11-24 02:43:05+00
15,Maduro out in 2025?,0xafc235557ace53ff0b0d2e93392314a7c3f3daab26a7...,3.464140e+07,2026-01-01 08:30:59+00
16,"Will Bitcoin reach $1,000,000 by December 31, ...",0xd8b9ff369452daebce1ac8cb6a29d6817903e8516835...,3.139461e+07,2026-01-01 07:20:31+00
17,Will George Russell be the 2025 Drivers Champion?,0x7e8953cc66f9dabfe80fb0d1a9284bffb7a293f700b2...,2.969811e+07,2025-11-10 06:35:19+00
18,Will Brad Lander win the 2025 NYC mayoral elec...,0x34c989bada239153e86a009b3d25539db4c86fc4df3e...,2.924689e+07,2025-11-05 06:13:17+00
19,Will Saudi Aramco be the largest company in th...,0xb1a6136ad23d19526c4929d2e79c79e999628de931ca...,2.524078e+07,2026-01-01 01:11:43+00
20,Will Eric Adams win the 2025 NYC mayoral elect...,0x846ce700a217ec7b75b8d078450f7e88eb5f44c76c12...,2.449801e+07,2025-11-05 06:12:19+00
21,Will Octavian Berceanu be the next Mayor of Bu...,0x2017c048aeee624d3597ffd0c2273a0e2c2aec4dfb89...,2.030469e+07,2025-12-08 04:23:11+00
22,Will Zellnor Myrie win the 2025 NYC mayoral el...,0xcdec3de1f9c73e9ade1d33dde14b96e7241d0cc87f04...,1.938366e+07,2025-11-05 06:13:17+00
23,"Will Bitcoin reach $200,000 by December 31, 2025?",0x4e2887e913cd6e091c9b07b5e4013b24f372453efa6f...,1.927571e+07,2026-01-01 07:16:21+00
24,"Will Ethereum hit $5,000 by December 31?",0xeeb92ddd77d671d1f9ea1f5727208d1fa91896a6d1f6...,1.846774e+07,2026-01-01 07:18:23+00
25,MicroStrategy sells any Bitcoin in 2025?,0x19ee98e348c0ccb341d1b9566fa14521566e9b2ea7ae...,1.797616e+07,2026-01-05 04:22:25+00
26,Will the New England Patriots win Super Bowl 2...,0xc914317b14972d5d15f30740d3bdf32f4028877c13b9...,1.788442e+07,2026-02-09 07:20:11+00
27,Will Rudy Giuliani win the 2025 NYC mayoral el...,0xee44d5936019f87f0fee643d930ac34139e7211ebdde...,1.739921e+07,2025-11-05 06:14:19+00
28,Will Adrienne Adams win the 2025 NYC mayoral e...,0xbb50a8be669052c941c30a8892b48ba104fb09ffd7d8...,1.717274e+07,2025-11-05 06:14:21+00
29,Trump declassifies UFO files in 2025?,0x2865bc483dd523f4a36eb961f7467c8635ee9a13f397...,1.668024e+07,2025-12-10 00:27:58+00

In [37]:
import requests
import time

top30_trades = []

for i, condition_id in enumerate(top30["conditionId"], 1):
    cursor = None
    market_count = 0

    while True:
        params = {
            "condition": condition_id,
            "limit": 1000
        }
        if cursor:
            params["cursor"] = cursor

        r = requests.get(
            "https://data-api.polymarket.com/v2/trades",
            params=params
        )

        if r.status_code != 200:
            print("Error:", i, r.status_code, condition_id)
            break

        data = r.json()
        trades = data.get("data", [])
        top30_trades.extend(trades)
        market_count += len(trades)

        cursor = data.get("pagination", {}).get("next_cursor")

        if not cursor:
            break

        time.sleep(0.1)

    print(f"{i}/30 | trades: {market_count}")

print("TOTAL TRADES:", len(top30_trades))

1/30 | trades: 240993
2/30 | trades: 94806
3/30 | trades: 58744
4/30 | trades: 40657
5/30 | trades: 62147
6/30 | trades: 57475
7/30 | trades: 40338
8/30 | trades: 45122
9/30 | trades: 39516
10/30 | trades: 14172
11/30 | trades: 65422
12/30 | trades: 41731
13/30 | trades: 39040
14/30 | trades: 41442
15/30 | trades: 35455
16/30 | trades: 47279
17/30 | trades: 57411
18/30 | trades: 37274
19/30 | trades: 30964
20/30 | trades: 14822
21/30 | trades: 51589
22/30 | trades: 2496
23/30 | trades: 10228
24/30 | trades: 25035
25/30 | trades: 33010
26/30 | trades: 13271
27/30 | trades: 70365
28/30 | trades: 6224
29/30 | trades: 2971
30/30 | trades: 11315
TOTAL TRADES: 1331314

In [38]:
top30_trades_df = pd.DataFrame(top30_trades)

top30_trades_df["date"] = pd.to_datetime(
    top30_trades_df["timestamp"],
    unit="s",
    utc=True
)

top30_period = top30_trades_df[
    (top30_trades_df["date"] >= pd.Timestamp("2025-11-01", tz="UTC")) &
    (top30_trades_df["date"] < pd.Timestamp("2026-05-01", tz="UTC"))
].copy()

top30_period["notional"] = (
    top30_period["size"] * top30_period["price"]
)

print("All trades:", len(top30_trades_df))
print("Period trades:", len(top30_period))
print("Unique wallets:", top30_period["proxy_wallet"].nunique())

All trades: 1331314
Period trades: 383615
Unique wallets: 96039

In [40]:
market_results = period_markets[
    ["conditionId", "question", "closedTime", "outcomes", "outcomePrices"]
].copy()

top30_period = top30_period.merge(
    market_results,
    on="conditionId",
    how="left"
)

print(
    top30_period[
        ["question", "outcomes", "outcomePrices"]
    ].drop_duplicates().head(10).to_string(index=False)
)

KeyError: 'conditionId'

In [41]:
print(top30_period.columns.tolist())

['proxy_wallet', 'side', 'token_id', 'condition_id', 'size', 'price', 'timestamp', 'title', 'slug', 'icon', 'event_slug', 'outcome', 'outcome_index', 'name', 'pseudonym', 'bio', 'profile_image', 'profile_image_optimized', 'transaction_hash', 'date', 'notional']

In [42]:
market_results = period_markets[
    ["conditionId", "question", "closedTime", "outcomes", "outcomePrices"]
].copy()

market_results["winning_outcome"] = market_results.apply(
    lambda x: x["outcomes"][x["outcomePrices"].index("1")]
    if "1" in x["outcomePrices"] else None,
    axis=1
)

print(
    market_results[
        ["question", "winning_outcome"]
    ].head(10).to_string(index=False)
)

                                       question winning_outcome
                         Fed rate hike in 2025?
                          US recession in 2025?
                Fed emergency rate cut in 2025?
                      Tether insolvent in 2025?
                            USDT depeg in 2025?
                      Weed rescheduled in 2025?
                    Ukraine joins NATO in 2025?
Khamenei out as Supreme Leader of Iran in 2025?
             Nuclear weapon detonation in 2025?
            Russia x Ukraine ceasefire in 2025?

In [43]:
import ast

def get_winner(outcomes, prices):
    try:
        if isinstance(outcomes, str):
            outcomes = ast.literal_eval(outcomes)
        if isinstance(prices, str):
            prices = ast.literal_eval(prices)

        prices = [float(x) for x in prices]

        if 1.0 in prices:
            return outcomes[prices.index(1.0)]
    except:
        pass

    return None

market_results["winning_outcome"] = market_results.apply(
    lambda x: get_winner(x["outcomes"], x["outcomePrices"]),
    axis=1
)

print(
    market_results[
        ["question", "winning_outcome"]
    ].head(15).to_string(index=False)
)

                                       question winning_outcome
                         Fed rate hike in 2025?              No
                          US recession in 2025?              No
                Fed emergency rate cut in 2025?              No
                      Tether insolvent in 2025?              No
                            USDT depeg in 2025?              No
                      Weed rescheduled in 2025?              No
                    Ukraine joins NATO in 2025?              No
Khamenei out as Supreme Leader of Iran in 2025?              No
             Nuclear weapon detonation in 2025?              No
            Russia x Ukraine ceasefire in 2025?              No
      Putin out as President of Russia in 2025?              No
                         Netanyahu out by 2025?              No
           Will 2 Fed rate cuts happen in 2025?              No
           Will 3 Fed rate cuts happen in 2025?             Yes
           Will 4 Fed rate cuts happen in 2025?              No

In [44]:
winner_map = dict(
    zip(
        market_results["conditionId"],
        market_results["winning_outcome"]
    )
)

top30_period["winning_outcome"] = (
    top30_period["condition_id"].map(winner_map)
)

print(
    top30_period[
        ["question", "outcome", "winning_outcome"]
    ].head(10).to_string(index=False)
)

KeyError: "['question'] not in index"

In [45]:
print(
    top30_period[
        ["condition_id", "outcome", "winning_outcome"]
    ].head(10).to_string(index=False)
)

                                                      condition_id outcome winning_outcome
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes             Yes
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes             Yes
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes             Yes
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes             Yes
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes             Yes
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes             Yes
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes             Yes
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes             Yes
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes             Yes
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes             Yes

In [46]:
resolution_map = dict(
    zip(
        market_results["conditionId"],
        pd.to_datetime(
            market_results["closedTime"],
            utc=True,
            format="mixed"
        )
    )
)

top30_period["resolution_time"] = (
    top30_period["condition_id"].map(resolution_map)
)

top30_period["hours_to_resolution"] = (
    (
        top30_period["resolution_time"]
        - top30_period["date"]
    ).dt.total_seconds() / 3600
)

print(
    top30_period[
        ["date", "resolution_time", "hours_to_resolution"]
    ].head(10).to_string(index=False)
)

                     date           resolution_time  hours_to_resolution
2025-11-05 05:45:05+00:00 2025-11-05 05:44:47+00:00            -0.005000
2025-11-05 05:44:47+00:00 2025-11-05 05:44:47+00:00             0.000000
2025-11-05 05:44:19+00:00 2025-11-05 05:44:47+00:00             0.007778
2025-11-05 05:43:57+00:00 2025-11-05 05:44:47+00:00             0.013889
2025-11-05 05:43:43+00:00 2025-11-05 05:44:47+00:00             0.017778
2025-11-05 05:43:07+00:00 2025-11-05 05:44:47+00:00             0.027778
2025-11-05 05:43:07+00:00 2025-11-05 05:44:47+00:00             0.027778
2025-11-05 05:42:59+00:00 2025-11-05 05:44:47+00:00             0.030000
2025-11-05 05:42:01+00:00 2025-11-05 05:44:47+00:00             0.046111
2025-11-05 05:41:53+00:00 2025-11-05 05:44:47+00:00             0.048333

In [47]:
winning_buys = top30_period[
    (top30_period["side"] == "BUY") &
    (top30_period["outcome"] == top30_period["winning_outcome"]) &
    (top30_period["hours_to_resolution"] >= 6) &
    (top30_period["hours_to_resolution"] <= 72)
].copy()

print("Количество таких сделок:", len(winning_buys))
print("Уникальных кошельков:", winning_buys["proxy_wallet"].nunique())

print(
    winning_buys[
        ["condition_id", "outcome", "price",
         "notional", "hours_to_resolution"]
    ].head(10).to_string(index=False)
)

Количество таких сделок: 32815
Уникальных кошельков: 15042
                                                      condition_id outcome    price     notional  hours_to_resolution
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes 0.952413    12.599984             6.009444
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes 0.954306 27989.369985             6.010556
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes 0.953878 74999.999980             6.013889
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes 0.951000    99.999998             6.027778
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes 0.950516 13242.179996             6.036111
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes 0.949000     8.999999             6.052222
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes 0.949000   800.234760             6.056667
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes 0.949000    49.999981             6.061111
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes 0.948953    99.999998             6.067222
0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9     Yes 0.948332   613.499999             6.082222

In [48]:
wallet_repeatability = (
    winning_buys
    .groupby("proxy_wallet")
    .agg(
        markets=("condition_id", "nunique"),
        trades=("proxy_wallet", "size"),
        total_notional=("notional", "sum"),
        avg_entry=("price", "mean"),
        earliest_entry=("hours_to_resolution", "max")
    )
    .reset_index()
)

print(
    wallet_repeatability
    .sort_values(
        ["markets", "total_notional"],
        ascending=[False, False]
    )
    .head(20)
    .to_string(index=False)
)

                              proxy_wallet  markets  trades  total_notional  avg_entry  earliest_entry
0xe8dd7741ccb12350957ec71e9ee332e0d1e6ec86       10     608    2.629765e+05   0.977430       71.644722
0xd218e474776403a330142299f7796e8ba32eb5c9        7     442    4.462465e+05   0.914012       70.161111
0xb6fa57039ea79185895500dbd0067c288594abcf        7     192    7.005365e+04   0.937145       67.949444
0x3f7aee8f1fafcd873343105b24f83f3f98a9248e        6    3205    1.350942e+06   0.948939       71.430556
0x63d43bbb87f85af03b8f2f9e2fad7b54334fa2f1        6     460    3.611406e+05   0.957343       71.238611
0x1fad9860ab0d21c8668a13accf25d6eb3c11b5b2        5       6    2.868021e+05   0.998667       67.960556
0xca8e9533bf61136f39c31e76e36b2087c3dca742        5      30    2.190477e+05   0.998867       71.848611
0xcd91a549956854fdc38efad7e80ff5da8f5432b8        5     326    9.721189e+04   0.973532       66.347500
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1        4      18    1.271758e+05   0.939711       51.914444
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8        4      24    6.647836e+04   0.927875       71.363333
0xbacd00c9080a82ded56f504ee8810af732b0ab35        4      39    3.797997e+04   0.818342       61.076111
0x30cecdf29f069563ea21b8ae94492e41e53a6b2b        4     241    1.288253e+04   0.837801       71.470000
0x23cc4d606d11eefaccb6609195322e1885284f5a        4       5    1.089504e+03   0.844800       47.241944
0xcb29acdb7f82711b97dac80717d28f9af99776eb        4       4    7.860787e+02   0.998750       42.563333
0xe4cfbb89c05d3429280c69969aee2cfb7a4678c4        4      16    3.809495e+02   0.998500       71.644167
0x67ebd5679a51836b00133e134e450a9e52cda4e9        4       4    3.657525e+02   0.985750       45.571111
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db        3      21    2.176377e+05   0.913187       64.715556
0xc6dd722558dbfbd8fa780efcbe819ed8c6604b9f        3      58    1.968413e+05   0.904698       51.619444
0xe25b9180f5687aa85bd94ee309bb72a464320f1b        3       4    1.789359e+05   0.939565       70.977222
0xc4d1a863e9cc45d02ba22d3a1ae9ba7822018ce8        3      10    1.510446e+05   0.958107       34.663889

In [50]:
large_winning_buys = winning_buys[
    winning_buys["notional"] >= 1000
].copy()

print("Крупных сделок:", len(large_winning_buys))
print("Кошельков:", large_winning_buys["proxy_wallet"].nunique())

Крупных сделок: 3083
Кошельков: 1186

In [51]:
large_wallets = (
    large_winning_buys
    .groupby("proxy_wallet")
    .agg(
        markets=("condition_id", "nunique"),
        trades=("proxy_wallet", "size"),
        total_notional=("notional", "sum"),
        avg_entry=("price", "mean"),
        avg_hours_before=("hours_to_resolution", "mean")
    )
    .reset_index()
)

top_wallets = (
    large_wallets
    .sort_values(
        ["markets", "total_notional"],
        ascending=[False, False]
    )
    .head(30)
)

print(top_wallets.to_string(index=False))

                              proxy_wallet  markets  trades  total_notional  avg_entry  avg_hours_before
0x1fad9860ab0d21c8668a13accf25d6eb3c11b5b2        5       6   286802.073490   0.998667         40.487963
0xca8e9533bf61136f39c31e76e36b2087c3dca742        5      30   219047.694000   0.998867         44.597046
0xd218e474776403a330142299f7796e8ba32eb5c9        4      88   397057.061241   0.948773         29.638750
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1        4      14   125251.314738   0.939914         16.727599
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8        4      17    64900.855830   0.922118         27.829265
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db        3      17   216145.427042   0.925326         31.296405
0xc6dd722558dbfbd8fa780efcbe819ed8c6604b9f        3      33   188224.924660   0.935464         25.716237
0xc4d1a863e9cc45d02ba22d3a1ae9ba7822018ce8        3      10   151044.598361   0.958107         17.708389
0x448861155279dbf833d041b963e3ac854599e319        3       8   145705.491890   0.943816         13.914861
0x088ffbbc6f2c0b3839d2832e75f37e1bcecbc9e7        3       8   134918.391400   0.943123         40.137118
0x7ba5354929bf388707f397c8b21b8322dc954252        3      14    72917.961710   0.907838         34.802262
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b        3      13    71988.958340   0.939116         19.012308
0xc02147dee42356b7a4edbb1c35ac4ffa95f61fa8        3      12    39501.866970   0.983232         26.242500
0xbacd00c9080a82ded56f504ee8810af732b0ab35        3      12    30293.575900   0.868722         36.982014
0x72a22d4d155079da8f50c89d4c6c03b6428e7b65        3       5    22570.696140   0.936385         38.735000
0x0e3226217752d7247c67b870b72b99ba3e20535b        3       4    10923.755840   0.919106         20.437222
0xe76958f1daae08939ecd09faa5c6b522b7458797        3       3     7683.388920   0.999000         44.243796
0xdd225a03cd7ed89e3931906c67c75ab31cf89ef1        3       4     7489.658860   0.896250         30.668958
0x3f7aee8f1fafcd873343105b24f83f3f98a9248e        2     340   851656.212090   0.950812         33.502319
0x63d43bbb87f85af03b8f2f9e2fad7b54334fa2f1        2     124   283827.680590   0.964927         29.314176
0x000d257d2dc7616feaef4ae0f14600fdf50a758e        2      25   238492.742083   0.953405         18.263144
0xe8dd7741ccb12350957ec71e9ee332e0d1e6ec86        2     107   200628.507629   0.976392         34.776745
0xe25b9180f5687aa85bd94ee309bb72a464320f1b        2       3   178843.519404   0.959420         52.192222
0xc8ab97a9089a9ff7e6ef0688e6e591a066946418        2       6   173066.544259   0.979905         23.648935
0xb48b9192dc52eed724fa58c66fa8926d06a3648e        2      19   112593.381230   0.973127         29.116023
0xc5adc0dc256fb943da868b2f8f6e63f13921b0cf        2       3   102920.379460   0.997323         29.533889
0xc25427ea224b8f9fa2df801233f944006ed33f73        2       6    91307.836980   0.989333         18.884213
0x241f846866c2de4fb67cdb0ca6b963d85e56ef50        2       5    76082.619991   0.913400         29.989889
0x85d575c99b977e9e39543747c859c83b727aaece        2       4    72037.809940   0.927250         36.690972
0xa102b434ce441a3119e146f75ed6276ee1a836d9        2       4    70214.299120   0.985750         23.626042

In [52]:
shortlist_wallets = top_wallets["proxy_wallet"].tolist()

shortlist_trades = large_winning_buys[
    large_winning_buys["proxy_wallet"].isin(shortlist_wallets)
].copy()

print("Сделок в shortlist:", len(shortlist_trades))
print("Кошельков:", shortlist_trades["proxy_wallet"].nunique())

Сделок в shortlist: 944
Кошельков: 30

In [53]:
def max_price_next_6h(trades, buy_time, outcome):
    end_time = buy_time + pd.Timedelta(hours=6)

    future = trades[
        (trades["date"] > buy_time) &
        (trades["date"] <= end_time) &
        (trades["outcome"] == outcome)
    ]

    if len(future) == 0:
        return None

    return future["price"].max()


shortlist_trades["max_price_6h"] = shortlist_trades.apply(
    lambda x: max_price_next_6h(
        top30_period[
            top30_period["condition_id"] == x["condition_id"]
        ],
        x["date"],
        x["outcome"]
    ),
    axis=1
)

shortlist_trades["move_6h"] = (
    shortlist_trades["max_price_6h"]
    - shortlist_trades["price"]
)

print(
    shortlist_trades["move_6h"].describe()
)

count    944.000000
mean       0.012745
std        0.024524
min       -0.001000
25%        0.000000
50%        0.003900
75%        0.015000
max        0.321000
Name: move_6h, dtype: float64

In [54]:
final_scores = (
    shortlist_trades
    .groupby("proxy_wallet")
    .agg(
        markets=("condition_id", "nunique"),
        trades=("proxy_wallet", "size"),
        total_notional=("notional", "sum"),
        avg_entry=("price", "mean"),
        avg_hours_before=("hours_to_resolution", "mean"),
        avg_move_6h=("move_6h", "mean")
    )
    .reset_index()
)

# Базовый score
final_scores["score"] = (
    final_scores["markets"] * 20
    + final_scores["avg_move_6h"] * 1000
    + (final_scores["total_notional"] / 100000) * 5
)

# Штраф за очень большое количество сделок
final_scores.loc[
    final_scores["trades"] > 200,
    "score"
] -= 20

final_ranking = (
    final_scores
    .sort_values("score", ascending=False)
    .head(15)
)

print(
    final_ranking.to_string(index=False)
)

                              proxy_wallet  markets  trades  total_notional  avg_entry  avg_hours_before  avg_move_6h      score
0xd218e474776403a330142299f7796e8ba32eb5c9        4      88   397057.061241   0.948773         29.638750     0.018859 118.711506
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1        4      14   125251.314738   0.939914         16.727599     0.029507 115.769856
0x1fad9860ab0d21c8668a13accf25d6eb3c11b5b2        5       6   286802.073490   0.998667         40.487963     0.000333 114.673437
0xbacd00c9080a82ded56f504ee8810af732b0ab35        3      12    30293.575900   0.868722         36.982014     0.052836 114.350617
0xca8e9533bf61136f39c31e76e36b2087c3dca742        5      30   219047.694000   0.998867         44.597046     0.000000 110.952385
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8        4      17    64900.855830   0.922118         27.829265     0.022647 105.892361
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b        3      13    71988.958340   0.939116         19.012308     0.041484 105.083745
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db        3      17   216145.427042   0.925326         31.296405     0.033086 103.893203
0x448861155279dbf833d041b963e3ac854599e319        3       8   145705.491890   0.943816         13.914861     0.031597  98.882167
0xdd225a03cd7ed89e3931906c67c75ab31cf89ef1        3       4     7489.658860   0.896250         30.668958     0.031000  91.374483
0xc6dd722558dbfbd8fa780efcbe819ed8c6604b9f        3      33   188224.924660   0.935464         25.716237     0.021930  91.341588
0xc4d1a863e9cc45d02ba22d3a1ae9ba7822018ce8        3      10   151044.598361   0.958107         17.708389     0.020793  88.344923
0x0e3226217752d7247c67b870b72b99ba3e20535b        3       4    10923.755840   0.919106         20.437222     0.023819  84.364838
0x72a22d4d155079da8f50c89d4c6c03b6428e7b65        3       5    22570.696140   0.936385         38.735000     0.017615  78.743656
0x000d257d2dc7616feaef4ae0f14600fdf50a758e        2      25   238492.742083   0.953405         18.263144     0.024475  76.399276

In [55]:
top10_wallets = final_ranking.head(10)["proxy_wallet"].tolist()

top10_trades = shortlist_trades[
    shortlist_trades["proxy_wallet"].isin(top10_wallets)
].copy()

print(
    top10_trades[
        [
            "proxy_wallet",
            "condition_id",
            "price",
            "notional",
            "hours_to_resolution",
            "move_6h"
        ]
    ]
    .sort_values(
        ["proxy_wallet", "move_6h"],
        ascending=[True, False]
    )
    .to_string(index=False)
)

                              proxy_wallet                                                       condition_id    price     notional  hours_to_resolution  move_6h
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.856127  1304.738000            35.171389 0.083873
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.870000  1992.213000            32.762500 0.080000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.870000  2876.594100            38.701389 0.060000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.870000  1840.050000            38.945278 0.060000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.930000  7013.464800            24.450278 0.052000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.930000  8370.297600            24.703611 0.050000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.939309 14934.861601            25.175833 0.036691
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.902000  1499.232240            22.047778 0.027000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.903000  6019.398000            22.018333 0.026000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.897857  1925.041400            39.929722 0.022143
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.970000  6698.917000            16.473611 0.021000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.976000  1952.000000            16.639167 0.015000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.977000 19540.000000            16.641944 0.014000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.940000  5526.889800            41.169722 0.010000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0xafc235557ace53ff0b0d2e93392314a7c3f3daab26a79050e985c11282f66df7 0.993000  4965.000000            64.715556 0.002000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.911246 30186.729501            27.219444 0.001754
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db 0xafc235557ace53ff0b0d2e93392314a7c3f3daab26a79050e985c11282f66df7 0.995000 99500.000000            45.273333 0.001000
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b3937363ec7c1ad1d13bee107e 0.884000  1206.668840            25.012222 0.040000
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.891000  7383.057660            24.167778 0.038000
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.891000  5906.643930            24.196111 0.038000
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.891000  2074.595490            24.228889 0.038000
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.892000  2044.018000            23.665556 0.037000
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b3937363ec7c1ad1d13bee107e 0.917000  3209.500000            15.869444 0.033000
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.962000  2900.430000            11.880833 0.028000
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b3937363ec7c1ad1d13bee107e 0.901000  1614.934380            22.041667 0.023000
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.937000  8876.922490            11.817778 0.021976
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b3937363ec7c1ad1d13bee107e 0.912000  5810.580000            18.448889 0.019000
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b3937363ec7c1ad1d13bee107e 0.906000  2368.030320            21.297222 0.018000
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.946000  5929.036080            10.798333 0.016544
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b3937363ec7c1ad1d13bee107e 0.945000  1564.674300            11.841667 0.016485
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b3937363ec7c1ad1d13bee107e 0.918000  4581.077040            19.986667 0.012000
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.940000  4139.308800            70.699444 0.004000
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.998000  1583.576500            71.363333 0.001000
0x12d6cccfc7470a3f4bafc53599a4779cbf2cf2a8 0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b3937363ec7c1ad1d13bee107e 0.945000  3707.802000            65.781667 0.001000
0x1fad9860ab0d21c8668a13accf25d6eb3c11b5b2 0x580ffec1f7b057910f9f596c80d203870f3028b04784a982d158d3581514299e 0.997000 30262.230130            10.660000 0.002000
0x1fad9860ab0d21c8668a13accf25d6eb3c11b5b2 0xf2d034812c1e871421eb6ca9afd30f2a03f0494fc910cc4cabc4515685b610cb 0.999000 64935.000000            53.940278 0.000000
0x1fad9860ab0d21c8668a13accf25d6eb3c11b5b2 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000 95904.000000            39.402222 0.000000
0x1fad9860ab0d21c8668a13accf25d6eb3c11b5b2 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000 29970.000000            67.960556 0.000000
0x1fad9860ab0d21c8668a13accf25d6eb3c11b5b2 0xd28f9dfab98d6b2a8a22d8ff7e8d109678fc8275710be17c96825301efce4a69 0.999000 63936.000000            56.620833 0.000000
0x1fad9860ab0d21c8668a13accf25d6eb3c11b5b2 0x2017c048aeee624d3597ffd0c2273a0e2c2aec4dfb89ef7505b8e08715636c3b 0.999000  1794.843360            14.343889 0.000000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b3937363ec7c1ad1d13bee107e 0.940000 21101.458400             8.249444 0.059000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.944000  6126.493920             7.735000 0.055000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.945000  1087.638300             7.624444 0.054000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.945000  3540.026700             8.971111 0.054000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.920000  2579.643200            14.018889 0.030000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.920997  2884.101590            13.962222 0.029003
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.931870 17681.979450            11.841111 0.027050
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.933927 41611.650978            11.836111 0.025049
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.927000  7405.886430            13.380556 0.023000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.930000  7392.886200            13.353889 0.020000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.913000  5934.563910            20.122222 0.016000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.977000  1120.228200            12.217500 0.011000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.932000  1059.068880            51.914444 0.010000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  5725.688580            38.959444 0.000000
0x448861155279dbf833d041b963e3ac854599e319 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.942549  9439.026050             8.045000 0.056451
0x448861155279dbf833d041b963e3ac854599e319 0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b3937363ec7c1ad1d13bee107e 0.942982  9742.886000             8.237222 0.056018
0x448861155279dbf833d041b963e3ac854599e319 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.945000  3259.163250             8.498889 0.054000
0x448861155279dbf833d041b963e3ac854599e319 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.925000 13533.675000            11.985000 0.029306
0x448861155279dbf833d041b963e3ac854599e319 0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b3937363ec7c1ad1d13bee107e 0.925000 37886.103750            12.195556 0.028000
0x448861155279dbf833d041b963e3ac854599e319 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.923000 25429.240720            12.113333 0.027000
0x448861155279dbf833d041b963e3ac854599e319 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.948000 18960.000000            42.204444 0.002000
0x448861155279dbf833d041b963e3ac854599e319 0xafc235557ace53ff0b0d2e93392314a7c3f3daab26a79050e985c11282f66df7 0.999000 27455.397120             8.039444 0.000000
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.857516  2160.940000            21.761944 0.133484
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.910187  2857.660600            21.143056 0.080813
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.930000  4132.920000            24.163056 0.059000
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.930000  4132.920000            24.174167 0.059000
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.930000  3099.690000            24.300833 0.052000
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.950000  5277.250000            23.580833 0.039000
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.970000  4793.361700            10.086667 0.024700
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.971422  9714.220360            10.085000 0.023278
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.976000  9760.000000             6.316111 0.023000
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.978380  4891.900000            10.017778 0.016320
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.905000  4525.000000            32.432778 0.015000
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.983000 12100.002580             8.525000 0.011700
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b 0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b3937363ec7c1ad1d13bee107e 0.917000  4543.093100            30.572778 0.002000
0xbacd00c9080a82ded56f504ee8810af732b0ab35 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.600000  1280.706000            50.235278 0.229595
0xbacd00c9080a82ded56f504ee8810af732b0ab35 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.661048  1458.510800            49.363611 0.168952
0xbacd00c9080a82ded56f504ee8810af732b0ab35 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.880000  1445.734400            30.825833 0.070000
0xbacd00c9080a82ded56f504ee8810af732b0ab35 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.930000  1476.012300            26.458056 0.046000
0xbacd00c9080a82ded56f504ee8810af732b0ab35 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.962000  2938.650260            10.848889 0.032700
0xbacd00c9080a82ded56f504ee8810af732b0ab35 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.837169  1150.270000            55.143056 0.022831
0xbacd00c9080a82ded56f504ee8810af732b0ab35 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.978000  1801.867200             9.376111 0.016700
0xbacd00c9080a82ded56f504ee8810af732b0ab35 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.835179  2597.447200            53.768611 0.014821
0xbacd00c9080a82ded56f504ee8810af732b0ab35 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.983000  4370.811200             7.833333 0.011700
0xbacd00c9080a82ded56f504ee8810af732b0ab35 0x2865bc483dd523f4a36eb961f7467c8635ee9a13f39748bad55f645ce1f61512 0.849268  1160.950000            55.141944 0.010732
0xbacd00c9080a82ded56f504ee8810af732b0ab35 0xebddfcf7b4401dade8b4031770a1ab942b01854f3bed453d5df9425cd9f211a9 0.916000  6891.150440            33.713333 0.008000
0xbacd00c9080a82ded56f504ee8810af732b0ab35 0xafc235557ace53ff0b0d2e93392314a7c3f3daab26a79050e985c11282f66df7 0.993000  3721.466100            61.076111 0.002000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xf2d034812c1e871421eb6ca9afd30f2a03f0494fc910cc4cabc4515685b610cb 0.999000  5614.380000            19.528056 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xf2d034812c1e871421eb6ca9afd30f2a03f0494fc910cc4cabc4515685b610cb 0.999000  5664.330000            23.104722 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xf2d034812c1e871421eb6ca9afd30f2a03f0494fc910cc4cabc4515685b610cb 0.999000  5694.300000            25.449444 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xf2d034812c1e871421eb6ca9afd30f2a03f0494fc910cc4cabc4515685b610cb 0.999000  5716.278000            71.848611 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  9260.730000            34.455000 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  9212.778000            35.482222 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  9240.750000            35.729444 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  9290.700000            36.473333 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  9290.700000            56.928333 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  9190.800000            57.300556 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  9345.645000            58.279444 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  9190.800000            58.746111 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  9290.700000            59.068889 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  9323.667000            60.127778 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  9290.700000            60.746667 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  9390.600000            60.931667 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  9340.650000            61.147222 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd7bd58d09efa1ff15be61cf30587e79444971ab125d55b2a88bf6ec04623a0d8 0.999000  9390.600000            61.382222 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd28f9dfab98d6b2a8a22d8ff7e8d109678fc8275710be17c96825301efce4a69 0.999000  5594.400000            22.710278 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd28f9dfab98d6b2a8a22d8ff7e8d109678fc8275710be17c96825301efce4a69 0.999000  5674.320000            26.164722 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xd28f9dfab98d6b2a8a22d8ff7e8d109678fc8275710be17c96825301efce4a69 0.999000  5674.320000            44.122500 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xc319ae3e39f6a0b441fd02d37058ee8af4133967a205c88c9243972deceddbee 0.999000  5634.360000            15.938333 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xc319ae3e39f6a0b441fd02d37058ee8af4133967a205c88c9243972deceddbee 0.999000  5674.320000            21.835278 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xc319ae3e39f6a0b441fd02d37058ee8af4133967a205c88c9243972deceddbee 0.999000  5682.312000            24.296111 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xc319ae3e39f6a0b441fd02d37058ee8af4133967a205c88c9243972deceddbee 0.999000  5693.301000            41.863611 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xc319ae3e39f6a0b441fd02d37058ee8af4133967a205c88c9243972deceddbee 0.999000  5705.289000            69.837500 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xf9915c09cfdb45b8ba1335620c1da05d12913ad1d43bbb15832a93609212c27e 0.998000  6017.940000            25.767778 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xf9915c09cfdb45b8ba1335620c1da05d12913ad1d43bbb15832a93609212c27e 0.998000  6087.800000            46.921111 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xf9915c09cfdb45b8ba1335620c1da05d12913ad1d43bbb15832a93609212c27e 0.998000  2694.600000            50.800000 0.000000
0xca8e9533bf61136f39c31e76e36b2087c3dca742 0xf9915c09cfdb45b8ba1335620c1da05d12913ad1d43bbb15832a93609212c27e 0.998000  6175.624000            70.924444 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9 0xc914317b14972d5d15f30740d3bdf32f4028877c13b9d7ccc78b4ba33f67fb1e 0.678000  1979.760000             7.860000 0.321000
0xd218e474776403a330142299f7796e8ba32eb5c9 0xc914317b14972d5d15f30740d3bdf32f4028877c13b9d7ccc78b4ba33f67fb1e 0.730000  5840.000000             6.944444 0.269000
0xd218e474776403a330142299f7796e8ba32eb5c9 0xc914317b14972d5d15f30740d3bdf32f4028877c13b9d7ccc78b4ba33f67fb1e 0.811000  1836.282420             6.268333 0.188000
0xd218e474776403a330142299f7796e8ba32eb5c9 0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b3937363ec7c1ad1d13bee107e 0.947000  3030.400000             7.391111 0.052000
0xd218e474776403a330142299f7796e8ba32eb5c9 0xc40cbb2d7f5d2c43c624bd5b1d0b18cd3d0682b3937363ec7c1ad1d13bee107e 0.947000 33941.957320             7.408889 0.052000

In [56]:
condition_to_question = dict(
    zip(
        market_results["conditionId"],
        market_results["question"]
    )
)

top5_wallets = [
    "0xd218e474776403a330142299f7796e8ba32eb5c9",
    "0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1",
    "0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db",
    "0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b",
    "0xbacd00c9080a82ded56f504ee8810af732b0ab35"
]

top5_details = shortlist_trades[
    shortlist_trades["proxy_wallet"].isin(top5_wallets)
].copy()

top5_details["market"] = top5_details["condition_id"].map(
    condition_to_question
)

print(
    top5_details[
        [
            "proxy_wallet",
            "market",
            "price",
            "notional",
            "hours_to_resolution",
            "move_6h"
        ]
    ]
    .sort_values(
        ["proxy_wallet", "hours_to_resolution"],
        ascending=[True, False]
    )
    .to_string(index=False)
)

                              proxy_wallet                                                 market    price     notional  hours_to_resolution  move_6h
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db                                    Maduro out in 2025? 0.993000  4965.000000            64.715556 0.002000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db                                    Maduro out in 2025? 0.995000 99500.000000            45.273333 0.001000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db                  Trump declassifies UFO files in 2025? 0.940000  5526.889800            41.169722 0.010000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db                  Trump declassifies UFO files in 2025? 0.897857  1925.041400            39.929722 0.022143
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db                  Trump declassifies UFO files in 2025? 0.870000  1840.050000            38.945278 0.060000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db                  Trump declassifies UFO files in 2025? 0.870000  2876.594100            38.701389 0.060000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db                  Trump declassifies UFO files in 2025? 0.856127  1304.738000            35.171389 0.083873
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db                  Trump declassifies UFO files in 2025? 0.870000  1992.213000            32.762500 0.080000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db Will Zohran Mamdani win the 2025 NYC mayoral election? 0.911246 30186.729501            27.219444 0.001754
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db                  Trump declassifies UFO files in 2025? 0.939309 14934.861601            25.175833 0.036691
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db                  Trump declassifies UFO files in 2025? 0.930000  8370.297600            24.703611 0.050000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db                  Trump declassifies UFO files in 2025? 0.930000  7013.464800            24.450278 0.052000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db Will Zohran Mamdani win the 2025 NYC mayoral election? 0.902000  1499.232240            22.047778 0.027000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db Will Zohran Mamdani win the 2025 NYC mayoral election? 0.903000  6019.398000            22.018333 0.026000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db                  Trump declassifies UFO files in 2025? 0.977000 19540.000000            16.641944 0.014000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db                  Trump declassifies UFO files in 2025? 0.976000  1952.000000            16.639167 0.015000
0x0c4b64af62a0ac3dd477e9f80ec3eaa18e92f6db                  Trump declassifies UFO files in 2025? 0.970000  6698.917000            16.473611 0.021000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 Will Zohran Mamdani win the 2025 NYC mayoral election? 0.932000  1059.068880            51.914444 0.010000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  5725.688580            38.959444 0.000000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 Will Zohran Mamdani win the 2025 NYC mayoral election? 0.913000  5934.563910            20.122222 0.016000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 Will Zohran Mamdani win the 2025 NYC mayoral election? 0.920000  2579.643200            14.018889 0.030000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 Will Zohran Mamdani win the 2025 NYC mayoral election? 0.920997  2884.101590            13.962222 0.029003
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 Will Zohran Mamdani win the 2025 NYC mayoral election? 0.927000  7405.886430            13.380556 0.023000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 Will Zohran Mamdani win the 2025 NYC mayoral election? 0.930000  7392.886200            13.353889 0.020000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1                  Trump declassifies UFO files in 2025? 0.977000  1120.228200            12.217500 0.011000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 Will Zohran Mamdani win the 2025 NYC mayoral election? 0.931870 17681.979450            11.841111 0.027050
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 Will Zohran Mamdani win the 2025 NYC mayoral election? 0.933927 41611.650978            11.836111 0.025049
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 Will Zohran Mamdani win the 2025 NYC mayoral election? 0.945000  3540.026700             8.971111 0.054000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.940000 21101.458400             8.249444 0.059000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 Will Zohran Mamdani win the 2025 NYC mayoral election? 0.944000  6126.493920             7.735000 0.055000
0x24c8cf69a0e0a17eee21f69d29752bfa32e823e1 Will Zohran Mamdani win the 2025 NYC mayoral election? 0.945000  1087.638300             7.624444 0.054000
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b Will Zohran Mamdani win the 2025 NYC mayoral election? 0.905000  4525.000000            32.432778 0.015000
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.917000  4543.093100            30.572778 0.002000
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b                  Trump declassifies UFO files in 2025? 0.930000  3099.690000            24.300833 0.052000
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b                  Trump declassifies UFO files in 2025? 0.930000  4132.920000            24.174167 0.059000
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b                  Trump declassifies UFO files in 2025? 0.930000  4132.920000            24.163056 0.059000
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b                  Trump declassifies UFO files in 2025? 0.950000  5277.250000            23.580833 0.039000
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b                  Trump declassifies UFO files in 2025? 0.857516  2160.940000            21.761944 0.133484
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b                  Trump declassifies UFO files in 2025? 0.910187  2857.660600            21.143056 0.080813
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b                  Trump declassifies UFO files in 2025? 0.970000  4793.361700            10.086667 0.024700
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b                  Trump declassifies UFO files in 2025? 0.971422  9714.220360            10.085000 0.023278
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b                  Trump declassifies UFO files in 2025? 0.978380  4891.900000            10.017778 0.016320
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b                  Trump declassifies UFO files in 2025? 0.983000 12100.002580             8.525000 0.011700
0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b                  Trump declassifies UFO files in 2025? 0.976000  9760.000000             6.316111 0.023000
0xbacd00c9080a82ded56f504ee8810af732b0ab35                                    Maduro out in 2025? 0.993000  3721.466100            61.076111 0.002000
0xbacd00c9080a82ded56f504ee8810af732b0ab35                  Trump declassifies UFO files in 2025? 0.837169  1150.270000            55.143056 0.022831
0xbacd00c9080a82ded56f504ee8810af732b0ab35                  Trump declassifies UFO files in 2025? 0.849268  1160.950000            55.141944 0.010732
0xbacd00c9080a82ded56f504ee8810af732b0ab35                  Trump declassifies UFO files in 2025? 0.835179  2597.447200            53.768611 0.014821
0xbacd00c9080a82ded56f504ee8810af732b0ab35                  Trump declassifies UFO files in 2025? 0.600000  1280.706000            50.235278 0.229595
0xbacd00c9080a82ded56f504ee8810af732b0ab35                  Trump declassifies UFO files in 2025? 0.661048  1458.510800            49.363611 0.168952
0xbacd00c9080a82ded56f504ee8810af732b0ab35 Will Zohran Mamdani win the 2025 NYC mayoral election? 0.916000  6891.150440            33.713333 0.008000
0xbacd00c9080a82ded56f504ee8810af732b0ab35                  Trump declassifies UFO files in 2025? 0.880000  1445.734400            30.825833 0.070000
0xbacd00c9080a82ded56f504ee8810af732b0ab35                  Trump declassifies UFO files in 2025? 0.930000  1476.012300            26.458056 0.046000
0xbacd00c9080a82ded56f504ee8810af732b0ab35                  Trump declassifies UFO files in 2025? 0.962000  2938.650260            10.848889 0.032700
0xbacd00c9080a82ded56f504ee8810af732b0ab35                  Trump declassifies UFO files in 2025? 0.978000  1801.867200             9.376111 0.016700
0xbacd00c9080a82ded56f504ee8810af732b0ab35                  Trump declassifies UFO files in 2025? 0.983000  4370.811200             7.833333 0.011700
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  8991.000000            65.630556 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  8991.000000            65.553889 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  8991.000000            65.385556 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  8991.000000            65.273889 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  8991.000000            61.373889 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  3046.300650            60.643889 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  1817.260920            60.300000 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  8991.000000            59.347222 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  7740.571680            58.870556 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  8982.688320            58.767778 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  8991.000000            56.295000 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  8991.000000            56.061111 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.935000  8415.000000            56.013333 0.010000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.935000  8415.000000            55.779444 0.010000
0xd218e474776403a330142299f7796e8ba32eb5c9        Will the Carolina Panthers win Super Bowl 2026? 0.994000  1252.440000            55.022222 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  5962.771260            53.137778 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  1843.304850            34.724444 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  2497.500000            34.703333 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  2673.723600            34.681667 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  3716.280000            34.668333 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  1693.974330            34.612778 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  8616.624750            34.429444 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.922000  3429.840000            34.386667 0.002000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  5118.296580            34.357778 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  1526.182290            34.348333 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  1087.511400            34.327778 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  8991.000000            34.318889 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  8991.000000            34.261111 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  1507.061430            34.171667 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  2817.180000            34.165556 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  1431.257310            34.136111 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  1238.760000            33.987778 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  2717.280000            33.983333 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  5494.500000            33.976667 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  4515.480000            33.960000 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  2237.760000            33.873333 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  3009.037950            33.836111 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  1203.615180            33.830000 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  1887.380730            33.828333 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  1498.500000            33.812778 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  3536.460000            33.805556 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.922000  1143.280000            33.706111 0.002000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.923000  2510.560000            33.701111 0.001000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.924000  4449.143160            33.695000 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.911000  4465.193620            32.530556 0.010000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.911000  1093.200000            32.521111 0.010000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.918000  1930.554000            32.440000 0.003000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.918000  8262.000000            32.437778 0.003000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.918019  2184.884990            31.249444 0.002981
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.888000  1342.442880            24.975000 0.036000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.896000  1035.202560            24.598333 0.028000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.902000  2677.965840            23.596667 0.022000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Curtis Sliwa win the 2025 NYC mayoral election? 0.999000  5261.752980            22.417778 0.000000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.906000  1721.400000            21.325556 0.018000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.914009  4350.683510            20.778333 0.009991
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.915000  1183.534200            20.769444 0.009000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.915000  1052.808150            20.019444 0.015000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.922000  8283.275660            19.380000 0.009000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.924000  1903.440000            19.215556 0.007000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.923000  1527.574230            19.044444 0.008000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.923000  1879.541820            19.035000 0.008000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.917038  1082.105000            17.305000 0.031962
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.920000  4342.400000            17.160556 0.029000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.917365  5926.178870            15.822222 0.032635
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.918256  2479.291920            15.802222 0.031744
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.918000  1064.880000            14.487222 0.032000
0xd218e474776403a330142299f7796e8ba32eb5c9     Will the New England Patriots win Super Bowl 2026? 0.684000  3424.788000            13.932222 0.001000
0xd218e474776403a330142299f7796e8ba32eb5c9     Will the New England Patriots win Super Bowl 2026? 0.684237  2353.776950            13.005556 0.033871
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.926000  1240.840000            12.747778 0.024000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.924000  4620.000000            12.218333 0.026000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.926000  1792.273000            12.153333 0.030000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.927000  1038.240000            12.089444 0.031000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.943070 18823.680250            11.851111 0.018415
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.946000  1381.160000            11.625556 0.018000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.945000  2192.400000            11.415556 0.019000
0xd218e474776403a330142299f7796e8ba32eb5c9   Will Andrew Cuomo win the 2025 NYC mayoral election? 0.947007  1799.313000            11.397222 0.016993

In [57]:
# 1. Top markets
top30.to_csv("top_markets.csv", index=False)

# 2. Ranked wallets
final_ranking.to_csv("wallet_ranking.csv", index=False)

# 3. Suspicious trades
shortlist_trades.to_csv("suspicious_trades.csv", index=False)

print("CSV files created:")
print("top_markets.csv")
print("wallet_ranking.csv")
print("suspicious_trades.csv")

CSV files created:
top_markets.csv
wallet_ranking.csv
suspicious_trades.csv

In [58]:
top5_csv = top5_details[
    [
        "proxy_wallet",
        "market",
        "price",
        "notional",
        "hours_to_resolution",
        "move_6h"
    ]
].copy()

top5_csv.to_csv("top5_investigation_trades.csv", index=False)

print("Created: top5_investigation_trades.csv")

Created: top5_investigation_trades.csv

In [ ]:
from google.colab import drive
drive.mount('/content/drive')